// Code generated by ent, DO NOT EDIT.

package repometa

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the repometa type in the database.
	Label = "repo_meta"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPrivateRepoID holds the string denoting the private_repo_id field in the database.
	FieldPrivateRepoID = "private_repo_id"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the repometa in the database.
	Table = "repo_meta"
)

// Columns holds all SQL columns for repometa fields.
var Columns = []string{
	FieldID,
	FieldPrivateRepoID,
	FieldDisplayName,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPrivateRepoID holds the default value on creation for the "private_repo_id" field.
	DefaultPrivateRepoID func() string
	// PrivateRepoIDValidator is a validator for the "private_repo_id" field. It is called by the builders before save.
	PrivateRepoIDValidator func(string) error
	// DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	DisplayNameValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the RepoMeta queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPrivateRepoID orders the results by the private_repo_id field.
func ByPrivateRepoID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrivateRepoID, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
