// Code generated by ent, DO NOT EDIT.

package repometa

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/khanakia/repolink-go/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldContainsFold(FieldID, id))
}

// PrivateRepoID applies equality check predicate on the "private_repo_id" field. It's identical to PrivateRepoIDEQ.
func PrivateRepoID(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEQ(FieldPrivateRepoID, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEQ(FieldDisplayName, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEQ(FieldCreatedAt, v))
}

// PrivateRepoIDEQ applies the EQ predicate on the "private_repo_id" field.
func PrivateRepoIDEQ(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEQ(FieldPrivateRepoID, v))
}

// PrivateRepoIDNEQ applies the NEQ predicate on the "private_repo_id" field.
func PrivateRepoIDNEQ(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNEQ(FieldPrivateRepoID, v))
}

// PrivateRepoIDIn applies the In predicate on the "private_repo_id" field.
func PrivateRepoIDIn(vs ...string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldIn(FieldPrivateRepoID, vs...))
}

// PrivateRepoIDNotIn applies the NotIn predicate on the "private_repo_id" field.
func PrivateRepoIDNotIn(vs ...string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNotIn(FieldPrivateRepoID, vs...))
}

// PrivateRepoIDGT applies the GT predicate on the "private_repo_id" field.
func PrivateRepoIDGT(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldGT(FieldPrivateRepoID, v))
}

// PrivateRepoIDGTE applies the GTE predicate on the "private_repo_id" field.
func PrivateRepoIDGTE(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldGTE(FieldPrivateRepoID, v))
}

// PrivateRepoIDLT applies the LT predicate on the "private_repo_id" field.
func PrivateRepoIDLT(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldLT(FieldPrivateRepoID, v))
}

// PrivateRepoIDLTE applies the LTE predicate on the "private_repo_id" field.
func PrivateRepoIDLTE(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldLTE(FieldPrivateRepoID, v))
}

// PrivateRepoIDContains applies the Contains predicate on the "private_repo_id" field.
func PrivateRepoIDContains(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldContains(FieldPrivateRepoID, v))
}

// PrivateRepoIDHasPrefix applies the HasPrefix predicate on the "private_repo_id" field.
func PrivateRepoIDHasPrefix(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldHasPrefix(FieldPrivateRepoID, v))
}

// PrivateRepoIDHasSuffix applies the HasSuffix predicate on the "private_repo_id" field.
func PrivateRepoIDHasSuffix(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldHasSuffix(FieldPrivateRepoID, v))
}

// PrivateRepoIDEqualFold applies the EqualFold predicate on the "private_repo_id" field.
func PrivateRepoIDEqualFold(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEqualFold(FieldPrivateRepoID, v))
}

// PrivateRepoIDContainsFold applies the ContainsFold predicate on the "private_repo_id" field.
func PrivateRepoIDContainsFold(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldContainsFold(FieldPrivateRepoID, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldContainsFold(FieldDisplayName, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RepoMeta) predicate.RepoMeta {
	return predicate.RepoMeta(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RepoMeta) predicate.RepoMeta {
	return predicate.RepoMeta(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RepoMeta) predicate.RepoMeta {
	return predicate.RepoMeta(sql.NotPredicates(p))
}
