// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ProfilesColumns holds the columns for the "profiles" table.
	ProfilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "hostname", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ProfilesTable holds the schema information for the "profiles" table.
	ProfilesTable = &schema.Table{
		Name:       "profiles",
		Columns:    ProfilesColumns,
		PrimaryKey: []*schema.Column{ProfilesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "profile_name_hostname",
				Unique:  true,
				Columns: []*schema.Column{ProfilesColumns[1], ProfilesColumns[2]},
			},
		},
	}
	// RepoMappingsColumns holds the columns for the "repo_mappings" table.
	RepoMappingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "source_rel", Type: field.TypeString},
		{Name: "repo_url", Type: field.TypeString},
		{Name: "target_rel", Type: field.TypeString},
		{Name: "link_name", Type: field.TypeString},
		{Name: "kind", Type: field.TypeEnum, Enums: []string{"dir", "file"}, Default: "dir"},
		{Name: "state", Type: field.TypeEnum, Enums: []string{"active", "paused", "trashed"}, Default: "active"},
		{Name: "created_by_email", Type: field.TypeString, Nullable: true},
		{Name: "created_by_name", Type: field.TypeString, Nullable: true},
		{Name: "updated_by_email", Type: field.TypeString, Nullable: true},
		{Name: "updated_by_name", Type: field.TypeString, Nullable: true},
		{Name: "notes", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// RepoMappingsTable holds the schema information for the "repo_mappings" table.
	RepoMappingsTable = &schema.Table{
		Name:       "repo_mappings",
		Columns:    RepoMappingsColumns,
		PrimaryKey: []*schema.Column{RepoMappingsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "repomapping_repo_url_target_rel_link_name",
				Unique:  true,
				Columns: []*schema.Column{RepoMappingsColumns[2], RepoMappingsColumns[3], RepoMappingsColumns[4]},
			},
			{
				Name:    "repomapping_source_rel_repo_url",
				Unique:  false,
				Columns: []*schema.Column{RepoMappingsColumns[1], RepoMappingsColumns[2]},
			},
		},
	}
	// RepoMetaColumns holds the columns for the "repo_meta" table.
	RepoMetaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "private_repo_id", Type: field.TypeString},
		{Name: "display_name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// RepoMetaTable holds the schema information for the "repo_meta" table.
	RepoMetaTable = &schema.Table{
		Name:       "repo_meta",
		Columns:    RepoMetaColumns,
		PrimaryKey: []*schema.Column{RepoMetaColumns[0]},
	}
	// RunLogsColumns holds the columns for the "run_logs" table.
	RunLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "profile_id", Type: field.TypeString},
		{Name: "mapping_id", Type: field.TypeString, Nullable: true},
		{Name: "op", Type: field.TypeEnum, Enums: []string{"setup", "sync", "unsync", "link", "unlink", "pause", "resume", "cleanup", "purge", "map_mv", "verify", "meta", "config"}},
		{Name: "result", Type: field.TypeEnum, Enums: []string{"ok", "error"}, Default: "ok"},
		{Name: "user_email", Type: field.TypeString, Nullable: true},
		{Name: "user_name", Type: field.TypeString, Nullable: true},
		{Name: "message", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// RunLogsTable holds the schema information for the "run_logs" table.
	RunLogsTable = &schema.Table{
		Name:       "run_logs",
		Columns:    RunLogsColumns,
		PrimaryKey: []*schema.Column{RunLogsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ProfilesTable,
		RepoMappingsTable,
		RepoMetaTable,
		RunLogsTable,
	}
)

func init() {
	ProfilesTable.Annotation = &entsql.Annotation{
		Table: "profiles",
	}
	RepoMappingsTable.Annotation = &entsql.Annotation{
		Table: "repo_mappings",
	}
	RepoMetaTable.Annotation = &entsql.Annotation{
		Table: "repo_meta",
	}
	RunLogsTable.Annotation = &entsql.Annotation{
		Table: "run_logs",
	}
}
