// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/khanakia/repolink-go/internal/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/khanakia/repolink-go/internal/ent/profile"
	"github.com/khanakia/repolink-go/internal/ent/repomapping"
	"github.com/khanakia/repolink-go/internal/ent/repometa"
	"github.com/khanakia/repolink-go/internal/ent/runlog"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Profile is the client for interacting with the Profile builders.
	Profile *ProfileClient
	// RepoMapping is the client for interacting with the RepoMapping builders.
	RepoMapping *RepoMappingClient
	// RepoMeta is the client for interacting with the RepoMeta builders.
	RepoMeta *RepoMetaClient
	// RunLog is the client for interacting with the RunLog builders.
	RunLog *RunLogClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Profile = NewProfileClient(c.config)
	c.RepoMapping = NewRepoMappingClient(c.config)
	c.RepoMeta = NewRepoMetaClient(c.config)
	c.RunLog = NewRunLogClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		Profile:     NewProfileClient(cfg),
		RepoMapping: NewRepoMappingClient(cfg),
		RepoMeta:    NewRepoMetaClient(cfg),
		RunLog:      NewRunLogClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		Profile:     NewProfileClient(cfg),
		RepoMapping: NewRepoMappingClient(cfg),
		RepoMeta:    NewRepoMetaClient(cfg),
		RunLog:      NewRunLogClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Profile.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Profile.Use(hooks...)
	c.RepoMapping.Use(hooks...)
	c.RepoMeta.Use(hooks...)
	c.RunLog.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Profile.Intercept(interceptors...)
	c.RepoMapping.Intercept(interceptors...)
	c.RepoMeta.Intercept(interceptors...)
	c.RunLog.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ProfileMutation:
		return c.Profile.mutate(ctx, m)
	case *RepoMappingMutation:
		return c.RepoMapping.mutate(ctx, m)
	case *RepoMetaMutation:
		return c.RepoMeta.mutate(ctx, m)
	case *RunLogMutation:
		return c.RunLog.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ProfileClient is a client for the Profile schema.
type ProfileClient struct {
	config
}

// NewProfileClient returns a client for the Profile from the given config.
func NewProfileClient(c config) *ProfileClient {
	return &ProfileClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `profile.Hooks(f(g(h())))`.
func (c *ProfileClient) Use(hooks ...Hook) {
	c.hooks.Profile = append(c.hooks.Profile, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `profile.Intercept(f(g(h())))`.
func (c *ProfileClient) Intercept(interceptors ...Interceptor) {
	c.inters.Profile = append(c.inters.Profile, interceptors...)
}

// Create returns a builder for creating a Profile entity.
func (c *ProfileClient) Create() *ProfileCreate {
	mutation := newProfileMutation(c.config, OpCreate)
	return &ProfileCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Profile entities.
func (c *ProfileClient) CreateBulk(builders ...*ProfileCreate) *ProfileCreateBulk {
	return &ProfileCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ProfileClient) MapCreateBulk(slice any, setFunc func(*ProfileCreate, int)) *ProfileCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProfileCreateBulk{err: fmt.Errorf("calling to ProfileClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProfileCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ProfileCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Profile.
func (c *ProfileClient) Update() *ProfileUpdate {
	mutation := newProfileMutation(c.config, OpUpdate)
	return &ProfileUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProfileClient) UpdateOne(_m *Profile) *ProfileUpdateOne {
	mutation := newProfileMutation(c.config, OpUpdateOne, withProfile(_m))
	return &ProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ProfileClient) UpdateOneID(id string) *ProfileUpdateOne {
	mutation := newProfileMutation(c.config, OpUpdateOne, withProfileID(id))
	return &ProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Profile.
func (c *ProfileClient) Delete() *ProfileDelete {
	mutation := newProfileMutation(c.config, OpDelete)
	return &ProfileDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ProfileClient) DeleteOne(_m *Profile) *ProfileDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ProfileClient) DeleteOneID(id string) *ProfileDeleteOne {
	builder := c.Delete().Where(profile.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProfileDeleteOne{builder}
}

// Query returns a query builder for Profile.
func (c *ProfileClient) Query() *ProfileQuery {
	return &ProfileQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeProfile},
		inters: c.Interceptors(),
	}
}

// Get returns a Profile entity by its id.
func (c *ProfileClient) Get(ctx context.Context, id string) (*Profile, error) {
	return c.Query().Where(profile.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ProfileClient) GetX(ctx context.Context, id string) *Profile {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ProfileClient) Hooks() []Hook {
	return c.hooks.Profile
}

// Interceptors returns the client interceptors.
func (c *ProfileClient) Interceptors() []Interceptor {
	return c.inters.Profile
}

func (c *ProfileClient) mutate(ctx context.Context, m *ProfileMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProfileCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProfileUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProfileDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Profile mutation op: %q", m.Op())
	}
}

// RepoMappingClient is a client for the RepoMapping schema.
type RepoMappingClient struct {
	config
}

// NewRepoMappingClient returns a client for the RepoMapping from the given config.
func NewRepoMappingClient(c config) *RepoMappingClient {
	return &RepoMappingClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `repomapping.Hooks(f(g(h())))`.
func (c *RepoMappingClient) Use(hooks ...Hook) {
	c.hooks.RepoMapping = append(c.hooks.RepoMapping, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `repomapping.Intercept(f(g(h())))`.
func (c *RepoMappingClient) Intercept(interceptors ...Interceptor) {
	c.inters.RepoMapping = append(c.inters.RepoMapping, interceptors...)
}

// Create returns a builder for creating a RepoMapping entity.
func (c *RepoMappingClient) Create() *RepoMappingCreate {
	mutation := newRepoMappingMutation(c.config, OpCreate)
	return &RepoMappingCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RepoMapping entities.
func (c *RepoMappingClient) CreateBulk(builders ...*RepoMappingCreate) *RepoMappingCreateBulk {
	return &RepoMappingCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RepoMappingClient) MapCreateBulk(slice any, setFunc func(*RepoMappingCreate, int)) *RepoMappingCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RepoMappingCreateBulk{err: fmt.Errorf("calling to RepoMappingClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RepoMappingCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RepoMappingCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RepoMapping.
func (c *RepoMappingClient) Update() *RepoMappingUpdate {
	mutation := newRepoMappingMutation(c.config, OpUpdate)
	return &RepoMappingUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RepoMappingClient) UpdateOne(_m *RepoMapping) *RepoMappingUpdateOne {
	mutation := newRepoMappingMutation(c.config, OpUpdateOne, withRepoMapping(_m))
	return &RepoMappingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RepoMappingClient) UpdateOneID(id string) *RepoMappingUpdateOne {
	mutation := newRepoMappingMutation(c.config, OpUpdateOne, withRepoMappingID(id))
	return &RepoMappingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RepoMapping.
func (c *RepoMappingClient) Delete() *RepoMappingDelete {
	mutation := newRepoMappingMutation(c.config, OpDelete)
	return &RepoMappingDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RepoMappingClient) DeleteOne(_m *RepoMapping) *RepoMappingDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RepoMappingClient) DeleteOneID(id string) *RepoMappingDeleteOne {
	builder := c.Delete().Where(repomapping.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RepoMappingDeleteOne{builder}
}

// Query returns a query builder for RepoMapping.
func (c *RepoMappingClient) Query() *RepoMappingQuery {
	return &RepoMappingQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRepoMapping},
		inters: c.Interceptors(),
	}
}

// Get returns a RepoMapping entity by its id.
func (c *RepoMappingClient) Get(ctx context.Context, id string) (*RepoMapping, error) {
	return c.Query().Where(repomapping.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RepoMappingClient) GetX(ctx context.Context, id string) *RepoMapping {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RepoMappingClient) Hooks() []Hook {
	return c.hooks.RepoMapping
}

// Interceptors returns the client interceptors.
func (c *RepoMappingClient) Interceptors() []Interceptor {
	return c.inters.RepoMapping
}

func (c *RepoMappingClient) mutate(ctx context.Context, m *RepoMappingMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RepoMappingCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RepoMappingUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RepoMappingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RepoMappingDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RepoMapping mutation op: %q", m.Op())
	}
}

// RepoMetaClient is a client for the RepoMeta schema.
type RepoMetaClient struct {
	config
}

// NewRepoMetaClient returns a client for the RepoMeta from the given config.
func NewRepoMetaClient(c config) *RepoMetaClient {
	return &RepoMetaClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `repometa.Hooks(f(g(h())))`.
func (c *RepoMetaClient) Use(hooks ...Hook) {
	c.hooks.RepoMeta = append(c.hooks.RepoMeta, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `repometa.Intercept(f(g(h())))`.
func (c *RepoMetaClient) Intercept(interceptors ...Interceptor) {
	c.inters.RepoMeta = append(c.inters.RepoMeta, interceptors...)
}

// Create returns a builder for creating a RepoMeta entity.
func (c *RepoMetaClient) Create() *RepoMetaCreate {
	mutation := newRepoMetaMutation(c.config, OpCreate)
	return &RepoMetaCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RepoMeta entities.
func (c *RepoMetaClient) CreateBulk(builders ...*RepoMetaCreate) *RepoMetaCreateBulk {
	return &RepoMetaCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RepoMetaClient) MapCreateBulk(slice any, setFunc func(*RepoMetaCreate, int)) *RepoMetaCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RepoMetaCreateBulk{err: fmt.Errorf("calling to RepoMetaClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RepoMetaCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RepoMetaCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RepoMeta.
func (c *RepoMetaClient) Update() *RepoMetaUpdate {
	mutation := newRepoMetaMutation(c.config, OpUpdate)
	return &RepoMetaUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RepoMetaClient) UpdateOne(_m *RepoMeta) *RepoMetaUpdateOne {
	mutation := newRepoMetaMutation(c.config, OpUpdateOne, withRepoMeta(_m))
	return &RepoMetaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RepoMetaClient) UpdateOneID(id string) *RepoMetaUpdateOne {
	mutation := newRepoMetaMutation(c.config, OpUpdateOne, withRepoMetaID(id))
	return &RepoMetaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RepoMeta.
func (c *RepoMetaClient) Delete() *RepoMetaDelete {
	mutation := newRepoMetaMutation(c.config, OpDelete)
	return &RepoMetaDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RepoMetaClient) DeleteOne(_m *RepoMeta) *RepoMetaDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RepoMetaClient) DeleteOneID(id string) *RepoMetaDeleteOne {
	builder := c.Delete().Where(repometa.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RepoMetaDeleteOne{builder}
}

// Query returns a query builder for RepoMeta.
func (c *RepoMetaClient) Query() *RepoMetaQuery {
	return &RepoMetaQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRepoMeta},
		inters: c.Interceptors(),
	}
}

// Get returns a RepoMeta entity by its id.
func (c *RepoMetaClient) Get(ctx context.Context, id string) (*RepoMeta, error) {
	return c.Query().Where(repometa.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RepoMetaClient) GetX(ctx context.Context, id string) *RepoMeta {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RepoMetaClient) Hooks() []Hook {
	return c.hooks.RepoMeta
}

// Interceptors returns the client interceptors.
func (c *RepoMetaClient) Interceptors() []Interceptor {
	return c.inters.RepoMeta
}

func (c *RepoMetaClient) mutate(ctx context.Context, m *RepoMetaMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RepoMetaCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RepoMetaUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RepoMetaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RepoMetaDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RepoMeta mutation op: %q", m.Op())
	}
}

// RunLogClient is a client for the RunLog schema.
type RunLogClient struct {
	config
}

// NewRunLogClient returns a client for the RunLog from the given config.
func NewRunLogClient(c config) *RunLogClient {
	return &RunLogClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `runlog.Hooks(f(g(h())))`.
func (c *RunLogClient) Use(hooks ...Hook) {
	c.hooks.RunLog = append(c.hooks.RunLog, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `runlog.Intercept(f(g(h())))`.
func (c *RunLogClient) Intercept(interceptors ...Interceptor) {
	c.inters.RunLog = append(c.inters.RunLog, interceptors...)
}

// Create returns a builder for creating a RunLog entity.
func (c *RunLogClient) Create() *RunLogCreate {
	mutation := newRunLogMutation(c.config, OpCreate)
	return &RunLogCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RunLog entities.
func (c *RunLogClient) CreateBulk(builders ...*RunLogCreate) *RunLogCreateBulk {
	return &RunLogCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RunLogClient) MapCreateBulk(slice any, setFunc func(*RunLogCreate, int)) *RunLogCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RunLogCreateBulk{err: fmt.Errorf("calling to RunLogClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RunLogCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RunLogCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RunLog.
func (c *RunLogClient) Update() *RunLogUpdate {
	mutation := newRunLogMutation(c.config, OpUpdate)
	return &RunLogUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RunLogClient) UpdateOne(_m *RunLog) *RunLogUpdateOne {
	mutation := newRunLogMutation(c.config, OpUpdateOne, withRunLog(_m))
	return &RunLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RunLogClient) UpdateOneID(id string) *RunLogUpdateOne {
	mutation := newRunLogMutation(c.config, OpUpdateOne, withRunLogID(id))
	return &RunLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RunLog.
func (c *RunLogClient) Delete() *RunLogDelete {
	mutation := newRunLogMutation(c.config, OpDelete)
	return &RunLogDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RunLogClient) DeleteOne(_m *RunLog) *RunLogDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RunLogClient) DeleteOneID(id string) *RunLogDeleteOne {
	builder := c.Delete().Where(runlog.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RunLogDeleteOne{builder}
}

// Query returns a query builder for RunLog.
func (c *RunLogClient) Query() *RunLogQuery {
	return &RunLogQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRunLog},
		inters: c.Interceptors(),
	}
}

// Get returns a RunLog entity by its id.
func (c *RunLogClient) Get(ctx context.Context, id string) (*RunLog, error) {
	return c.Query().Where(runlog.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RunLogClient) GetX(ctx context.Context, id string) *RunLog {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RunLogClient) Hooks() []Hook {
	return c.hooks.RunLog
}

// Interceptors returns the client interceptors.
func (c *RunLogClient) Interceptors() []Interceptor {
	return c.inters.RunLog
}

func (c *RunLogClient) mutate(ctx context.Context, m *RunLogMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RunLogCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RunLogUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RunLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RunLogDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RunLog mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Profile, RepoMapping, RepoMeta, RunLog []ent.Hook
	}
	inters struct {
		Profile, RepoMapping, RepoMeta, RunLog []ent.Interceptor
	}
)
