// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/khanakia/repolink-go/internal/ent/predicate"
	"github.com/khanakia/repolink-go/internal/ent/profile"
	"github.com/khanakia/repolink-go/internal/ent/repomapping"
	"github.com/khanakia/repolink-go/internal/ent/repometa"
	"github.com/khanakia/repolink-go/internal/ent/runlog"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeProfile     = "Profile"
	TypeRepoMapping = "RepoMapping"
	TypeRepoMeta    = "RepoMeta"
	TypeRunLog      = "RunLog"
)

// ProfileMutation represents an operation that mutates the Profile nodes in the graph.
type ProfileMutation struct {
	config
	op            Op
	typ           string
	id            *string
	name          *string
	hostname      *string
	created_at    *time.Time
	updated_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Profile, error)
	predicates    []predicate.Profile
}

var _ ent.Mutation = (*ProfileMutation)(nil)

// profileOption allows management of the mutation configuration using functional options.
type profileOption func(*ProfileMutation)

// newProfileMutation creates new mutation for the Profile entity.
func newProfileMutation(c config, op Op, opts ...profileOption) *ProfileMutation {
	m := &ProfileMutation{
		config:        c,
		op:            op,
		typ:           TypeProfile,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withProfileID sets the ID field of the mutation.
func withProfileID(id string) profileOption {
	return func(m *ProfileMutation) {
		var (
			err   error
			once  sync.Once
			value *Profile
		)
		m.oldValue = func(ctx context.Context) (*Profile, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Profile.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withProfile sets the old Profile of the mutation.
func withProfile(node *Profile) profileOption {
	return func(m *ProfileMutation) {
		m.oldValue = func(context.Context) (*Profile, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ProfileMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ProfileMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Profile entities.
func (m *ProfileMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ProfileMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ProfileMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Profile.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *ProfileMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *ProfileMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Profile entity.
// If the Profile object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProfileMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *ProfileMutation) ResetName() {
	m.name = nil
}

// SetHostname sets the "hostname" field.
func (m *ProfileMutation) SetHostname(s string) {
	m.hostname = &s
}

// Hostname returns the value of the "hostname" field in the mutation.
func (m *ProfileMutation) Hostname() (r string, exists bool) {
	v := m.hostname
	if v == nil {
		return
	}
	return *v, true
}

// OldHostname returns the old "hostname" field's value of the Profile entity.
// If the Profile object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProfileMutation) OldHostname(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHostname is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHostname requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHostname: %w", err)
	}
	return oldValue.Hostname, nil
}

// ResetHostname resets all changes to the "hostname" field.
func (m *ProfileMutation) ResetHostname() {
	m.hostname = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *ProfileMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *ProfileMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Profile entity.
// If the Profile object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProfileMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *ProfileMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *ProfileMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *ProfileMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Profile entity.
// If the Profile object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProfileMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *ProfileMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the ProfileMutation builder.
func (m *ProfileMutation) Where(ps ...predicate.Profile) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ProfileMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ProfileMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Profile, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ProfileMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ProfileMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Profile).
func (m *ProfileMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ProfileMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.name != nil {
		fields = append(fields, profile.FieldName)
	}
	if m.hostname != nil {
		fields = append(fields, profile.FieldHostname)
	}
	if m.created_at != nil {
		fields = append(fields, profile.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, profile.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ProfileMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case profile.FieldName:
		return m.Name()
	case profile.FieldHostname:
		return m.Hostname()
	case profile.FieldCreatedAt:
		return m.CreatedAt()
	case profile.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ProfileMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case profile.FieldName:
		return m.OldName(ctx)
	case profile.FieldHostname:
		return m.OldHostname(ctx)
	case profile.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case profile.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Profile field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ProfileMutation) SetField(name string, value ent.Value) error {
	switch name {
	case profile.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case profile.FieldHostname:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHostname(v)
		return nil
	case profile.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case profile.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Profile field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ProfileMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ProfileMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ProfileMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Profile numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ProfileMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ProfileMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ProfileMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Profile nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ProfileMutation) ResetField(name string) error {
	switch name {
	case profile.FieldName:
		m.ResetName()
		return nil
	case profile.FieldHostname:
		m.ResetHostname()
		return nil
	case profile.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case profile.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Profile field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ProfileMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ProfileMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ProfileMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ProfileMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ProfileMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ProfileMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ProfileMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Profile unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ProfileMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Profile edge %s", name)
}

// RepoMappingMutation represents an operation that mutates the RepoMapping nodes in the graph.
type RepoMappingMutation struct {
	config
	op               Op
	typ              string
	id               *string
	source_rel       *string
	repo_url         *string
	target_rel       *string
	link_name        *string
	kind             *repomapping.Kind
	state            *repomapping.State
	created_by_email *string
	created_by_name  *string
	updated_by_email *string
	updated_by_name  *string
	notes            *string
	created_at       *time.Time
	updated_at       *time.Time
	clearedFields    map[string]struct{}
	done             bool
	oldValue         func(context.Context) (*RepoMapping, error)
	predicates       []predicate.RepoMapping
}

var _ ent.Mutation = (*RepoMappingMutation)(nil)

// repomappingOption allows management of the mutation configuration using functional options.
type repomappingOption func(*RepoMappingMutation)

// newRepoMappingMutation creates new mutation for the RepoMapping entity.
func newRepoMappingMutation(c config, op Op, opts ...repomappingOption) *RepoMappingMutation {
	m := &RepoMappingMutation{
		config:        c,
		op:            op,
		typ:           TypeRepoMapping,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withRepoMappingID sets the ID field of the mutation.
func withRepoMappingID(id string) repomappingOption {
	return func(m *RepoMappingMutation) {
		var (
			err   error
			once  sync.Once
			value *RepoMapping
		)
		m.oldValue = func(ctx context.Context) (*RepoMapping, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().RepoMapping.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withRepoMapping sets the old RepoMapping of the mutation.
func withRepoMapping(node *RepoMapping) repomappingOption {
	return func(m *RepoMappingMutation) {
		m.oldValue = func(context.Context) (*RepoMapping, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m RepoMappingMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m RepoMappingMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of RepoMapping entities.
func (m *RepoMappingMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *RepoMappingMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *RepoMappingMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().RepoMapping.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetSourceRel sets the "source_rel" field.
func (m *RepoMappingMutation) SetSourceRel(s string) {
	m.source_rel = &s
}

// SourceRel returns the value of the "source_rel" field in the mutation.
func (m *RepoMappingMutation) SourceRel() (r string, exists bool) {
	v := m.source_rel
	if v == nil {
		return
	}
	return *v, true
}

// OldSourceRel returns the old "source_rel" field's value of the RepoMapping entity.
// If the RepoMapping object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepoMappingMutation) OldSourceRel(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSourceRel is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSourceRel requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSourceRel: %w", err)
	}
	return oldValue.SourceRel, nil
}

// ResetSourceRel resets all changes to the "source_rel" field.
func (m *RepoMappingMutation) ResetSourceRel() {
	m.source_rel = nil
}

// SetRepoURL sets the "repo_url" field.
func (m *RepoMappingMutation) SetRepoURL(s string) {
	m.repo_url = &s
}

// RepoURL returns the value of the "repo_url" field in the mutation.
func (m *RepoMappingMutation) RepoURL() (r string, exists bool) {
	v := m.repo_url
	if v == nil {
		return
	}
	return *v, true
}

// OldRepoURL returns the old "repo_url" field's value of the RepoMapping entity.
// If the RepoMapping object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepoMappingMutation) OldRepoURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRepoURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRepoURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRepoURL: %w", err)
	}
	return oldValue.RepoURL, nil
}

// ResetRepoURL resets all changes to the "repo_url" field.
func (m *RepoMappingMutation) ResetRepoURL() {
	m.repo_url = nil
}

// SetTargetRel sets the "target_rel" field.
func (m *RepoMappingMutation) SetTargetRel(s string) {
	m.target_rel = &s
}

// TargetRel returns the value of the "target_rel" field in the mutation.
func (m *RepoMappingMutation) TargetRel() (r string, exists bool) {
	v := m.target_rel
	if v == nil {
		return
	}
	return *v, true
}

// OldTargetRel returns the old "target_rel" field's value of the RepoMapping entity.
// If the RepoMapping object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepoMappingMutation) OldTargetRel(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTargetRel is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTargetRel requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTargetRel: %w", err)
	}
	return oldValue.TargetRel, nil
}

// ResetTargetRel resets all changes to the "target_rel" field.
func (m *RepoMappingMutation) ResetTargetRel() {
	m.target_rel = nil
}

// SetLinkName sets the "link_name" field.
func (m *RepoMappingMutation) SetLinkName(s string) {
	m.link_name = &s
}

// LinkName returns the value of the "link_name" field in the mutation.
func (m *RepoMappingMutation) LinkName() (r string, exists bool) {
	v := m.link_name
	if v == nil {
		return
	}
	return *v, true
}

// OldLinkName returns the old "link_name" field's value of the RepoMapping entity.
// If the RepoMapping object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepoMappingMutation) OldLinkName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLinkName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLinkName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLinkName: %w", err)
	}
	return oldValue.LinkName, nil
}

// ResetLinkName resets all changes to the "link_name" field.
func (m *RepoMappingMutation) ResetLinkName() {
	m.link_name = nil
}

// SetKind sets the "kind" field.
func (m *RepoMappingMutation) SetKind(r repomapping.Kind) {
	m.kind = &r
}

// Kind returns the value of the "kind" field in the mutation.
func (m *RepoMappingMutation) Kind() (r repomapping.Kind, exists bool) {
	v := m.kind
	if v == nil {
		return
	}
	return *v, true
}

// OldKind returns the old "kind" field's value of the RepoMapping entity.
// If the RepoMapping object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepoMappingMutation) OldKind(ctx context.Context) (v repomapping.Kind, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldKind is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldKind requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldKind: %w", err)
	}
	return oldValue.Kind, nil
}

// ResetKind resets all changes to the "kind" field.
func (m *RepoMappingMutation) ResetKind() {
	m.kind = nil
}

// SetState sets the "state" field.
func (m *RepoMappingMutation) SetState(r repomapping.State) {
	m.state = &r
}

// State returns the value of the "state" field in the mutation.
func (m *RepoMappingMutation) State() (r repomapping.State, exists bool) {
	v := m.state
	if v == nil {
		return
	}
	return *v, true
}

// OldState returns the old "state" field's value of the RepoMapping entity.
// If the RepoMapping object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepoMappingMutation) OldState(ctx context.Context) (v repomapping.State, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldState is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldState requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldState: %w", err)
	}
	return oldValue.State, nil
}

// ResetState resets all changes to the "state" field.
func (m *RepoMappingMutation) ResetState() {
	m.state = nil
}

// SetCreatedByEmail sets the "created_by_email" field.
func (m *RepoMappingMutation) SetCreatedByEmail(s string) {
	m.created_by_email = &s
}

// CreatedByEmail returns the value of the "created_by_email" field in the mutation.
func (m *RepoMappingMutation) CreatedByEmail() (r string, exists bool) {
	v := m.created_by_email
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedByEmail returns the old "created_by_email" field's value of the RepoMapping entity.
// If the RepoMapping object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepoMappingMutation) OldCreatedByEmail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedByEmail is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedByEmail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedByEmail: %w", err)
	}
	return oldValue.CreatedByEmail, nil
}

// ClearCreatedByEmail clears the value of the "created_by_email" field.
func (m *RepoMappingMutation) ClearCreatedByEmail() {
	m.created_by_email = nil
	m.clearedFields[repomapping.FieldCreatedByEmail] = struct{}{}
}

// CreatedByEmailCleared returns if the "created_by_email" field was cleared in this mutation.
func (m *RepoMappingMutation) CreatedByEmailCleared() bool {
	_, ok := m.clearedFields[repomapping.FieldCreatedByEmail]
	return ok
}

// ResetCreatedByEmail resets all changes to the "created_by_email" field.
func (m *RepoMappingMutation) ResetCreatedByEmail() {
	m.created_by_email = nil
	delete(m.clearedFields, repomapping.FieldCreatedByEmail)
}

// SetCreatedByName sets the "created_by_name" field.
func (m *RepoMappingMutation) SetCreatedByName(s string) {
	m.created_by_name = &s
}

// CreatedByName returns the value of the "created_by_name" field in the mutation.
func (m *RepoMappingMutation) CreatedByName() (r string, exists bool) {
	v := m.created_by_name
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedByName returns the old "created_by_name" field's value of the RepoMapping entity.
// If the RepoMapping object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepoMappingMutation) OldCreatedByName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedByName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedByName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedByName: %w", err)
	}
	return oldValue.CreatedByName, nil
}

// ClearCreatedByName clears the value of the "created_by_name" field.
func (m *RepoMappingMutation) ClearCreatedByName() {
	m.created_by_name = nil
	m.clearedFields[repomapping.FieldCreatedByName] = struct{}{}
}

// CreatedByNameCleared returns if the "created_by_name" field was cleared in this mutation.
func (m *RepoMappingMutation) CreatedByNameCleared() bool {
	_, ok := m.clearedFields[repomapping.FieldCreatedByName]
	return ok
}

// ResetCreatedByName resets all changes to the "created_by_name" field.
func (m *RepoMappingMutation) ResetCreatedByName() {
	m.created_by_name = nil
	delete(m.clearedFields, repomapping.FieldCreatedByName)
}

// SetUpdatedByEmail sets the "updated_by_email" field.
func (m *RepoMappingMutation) SetUpdatedByEmail(s string) {
	m.updated_by_email = &s
}

// UpdatedByEmail returns the value of the "updated_by_email" field in the mutation.
func (m *RepoMappingMutation) UpdatedByEmail() (r string, exists bool) {
	v := m.updated_by_email
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedByEmail returns the old "updated_by_email" field's value of the RepoMapping entity.
// If the RepoMapping object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepoMappingMutation) OldUpdatedByEmail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedByEmail is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedByEmail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedByEmail: %w", err)
	}
	return oldValue.UpdatedByEmail, nil
}

// ClearUpdatedByEmail clears the value of the "updated_by_email" field.
func (m *RepoMappingMutation) ClearUpdatedByEmail() {
	m.updated_by_email = nil
	m.clearedFields[repomapping.FieldUpdatedByEmail] = struct{}{}
}

// UpdatedByEmailCleared returns if the "updated_by_email" field was cleared in this mutation.
func (m *RepoMappingMutation) UpdatedByEmailCleared() bool {
	_, ok := m.clearedFields[repomapping.FieldUpdatedByEmail]
	return ok
}

// ResetUpdatedByEmail resets all changes to the "updated_by_email" field.
func (m *RepoMappingMutation) ResetUpdatedByEmail() {
	m.updated_by_email = nil
	delete(m.clearedFields, repomapping.FieldUpdatedByEmail)
}

// SetUpdatedByName sets the "updated_by_name" field.
func (m *RepoMappingMutation) SetUpdatedByName(s string) {
	m.updated_by_name = &s
}

// UpdatedByName returns the value of the "updated_by_name" field in the mutation.
func (m *RepoMappingMutation) UpdatedByName() (r string, exists bool) {
	v := m.updated_by_name
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedByName returns the old "updated_by_name" field's value of the RepoMapping entity.
// If the RepoMapping object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepoMappingMutation) OldUpdatedByName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedByName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedByName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedByName: %w", err)
	}
	return oldValue.UpdatedByName, nil
}

// ClearUpdatedByName clears the value of the "updated_by_name" field.
func (m *RepoMappingMutation) ClearUpdatedByName() {
	m.updated_by_name = nil
	m.clearedFields[repomapping.FieldUpdatedByName] = struct{}{}
}

// UpdatedByNameCleared returns if the "updated_by_name" field was cleared in this mutation.
func (m *RepoMappingMutation) UpdatedByNameCleared() bool {
	_, ok := m.clearedFields[repomapping.FieldUpdatedByName]
	return ok
}

// ResetUpdatedByName resets all changes to the "updated_by_name" field.
func (m *RepoMappingMutation) ResetUpdatedByName() {
	m.updated_by_name = nil
	delete(m.clearedFields, repomapping.FieldUpdatedByName)
}

// SetNotes sets the "notes" field.
func (m *RepoMappingMutation) SetNotes(s string) {
	m.notes = &s
}

// Notes returns the value of the "notes" field in the mutation.
func (m *RepoMappingMutation) Notes() (r string, exists bool) {
	v := m.notes
	if v == nil {
		return
	}
	return *v, true
}

// OldNotes returns the old "notes" field's value of the RepoMapping entity.
// If the RepoMapping object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepoMappingMutation) OldNotes(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNotes is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNotes requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNotes: %w", err)
	}
	return oldValue.Notes, nil
}

// ClearNotes clears the value of the "notes" field.
func (m *RepoMappingMutation) ClearNotes() {
	m.notes = nil
	m.clearedFields[repomapping.FieldNotes] = struct{}{}
}

// NotesCleared returns if the "notes" field was cleared in this mutation.
func (m *RepoMappingMutation) NotesCleared() bool {
	_, ok := m.clearedFields[repomapping.FieldNotes]
	return ok
}

// ResetNotes resets all changes to the "notes" field.
func (m *RepoMappingMutation) ResetNotes() {
	m.notes = nil
	delete(m.clearedFields, repomapping.FieldNotes)
}

// SetCreatedAt sets the "created_at" field.
func (m *RepoMappingMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *RepoMappingMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the RepoMapping entity.
// If the RepoMapping object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepoMappingMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *RepoMappingMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *RepoMappingMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *RepoMappingMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the RepoMapping entity.
// If the RepoMapping object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepoMappingMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *RepoMappingMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the RepoMappingMutation builder.
func (m *RepoMappingMutation) Where(ps ...predicate.RepoMapping) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the RepoMappingMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *RepoMappingMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.RepoMapping, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *RepoMappingMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *RepoMappingMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (RepoMapping).
func (m *RepoMappingMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *RepoMappingMutation) Fields() []string {
	fields := make([]string, 0, 13)
	if m.source_rel != nil {
		fields = append(fields, repomapping.FieldSourceRel)
	}
	if m.repo_url != nil {
		fields = append(fields, repomapping.FieldRepoURL)
	}
	if m.target_rel != nil {
		fields = append(fields, repomapping.FieldTargetRel)
	}
	if m.link_name != nil {
		fields = append(fields, repomapping.FieldLinkName)
	}
	if m.kind != nil {
		fields = append(fields, repomapping.FieldKind)
	}
	if m.state != nil {
		fields = append(fields, repomapping.FieldState)
	}
	if m.created_by_email != nil {
		fields = append(fields, repomapping.FieldCreatedByEmail)
	}
	if m.created_by_name != nil {
		fields = append(fields, repomapping.FieldCreatedByName)
	}
	if m.updated_by_email != nil {
		fields = append(fields, repomapping.FieldUpdatedByEmail)
	}
	if m.updated_by_name != nil {
		fields = append(fields, repomapping.FieldUpdatedByName)
	}
	if m.notes != nil {
		fields = append(fields, repomapping.FieldNotes)
	}
	if m.created_at != nil {
		fields = append(fields, repomapping.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, repomapping.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *RepoMappingMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case repomapping.FieldSourceRel:
		return m.SourceRel()
	case repomapping.FieldRepoURL:
		return m.RepoURL()
	case repomapping.FieldTargetRel:
		return m.TargetRel()
	case repomapping.FieldLinkName:
		return m.LinkName()
	case repomapping.FieldKind:
		return m.Kind()
	case repomapping.FieldState:
		return m.State()
	case repomapping.FieldCreatedByEmail:
		return m.CreatedByEmail()
	case repomapping.FieldCreatedByName:
		return m.CreatedByName()
	case repomapping.FieldUpdatedByEmail:
		return m.UpdatedByEmail()
	case repomapping.FieldUpdatedByName:
		return m.UpdatedByName()
	case repomapping.FieldNotes:
		return m.Notes()
	case repomapping.FieldCreatedAt:
		return m.CreatedAt()
	case repomapping.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *RepoMappingMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case repomapping.FieldSourceRel:
		return m.OldSourceRel(ctx)
	case repomapping.FieldRepoURL:
		return m.OldRepoURL(ctx)
	case repomapping.FieldTargetRel:
		return m.OldTargetRel(ctx)
	case repomapping.FieldLinkName:
		return m.OldLinkName(ctx)
	case repomapping.FieldKind:
		return m.OldKind(ctx)
	case repomapping.FieldState:
		return m.OldState(ctx)
	case repomapping.FieldCreatedByEmail:
		return m.OldCreatedByEmail(ctx)
	case repomapping.FieldCreatedByName:
		return m.OldCreatedByName(ctx)
	case repomapping.FieldUpdatedByEmail:
		return m.OldUpdatedByEmail(ctx)
	case repomapping.FieldUpdatedByName:
		return m.OldUpdatedByName(ctx)
	case repomapping.FieldNotes:
		return m.OldNotes(ctx)
	case repomapping.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case repomapping.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown RepoMapping field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RepoMappingMutation) SetField(name string, value ent.Value) error {
	switch name {
	case repomapping.FieldSourceRel:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSourceRel(v)
		return nil
	case repomapping.FieldRepoURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRepoURL(v)
		return nil
	case repomapping.FieldTargetRel:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTargetRel(v)
		return nil
	case repomapping.FieldLinkName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLinkName(v)
		return nil
	case repomapping.FieldKind:
		v, ok := value.(repomapping.Kind)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetKind(v)
		return nil
	case repomapping.FieldState:
		v, ok := value.(repomapping.State)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetState(v)
		return nil
	case repomapping.FieldCreatedByEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedByEmail(v)
		return nil
	case repomapping.FieldCreatedByName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedByName(v)
		return nil
	case repomapping.FieldUpdatedByEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedByEmail(v)
		return nil
	case repomapping.FieldUpdatedByName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedByName(v)
		return nil
	case repomapping.FieldNotes:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNotes(v)
		return nil
	case repomapping.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case repomapping.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown RepoMapping field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *RepoMappingMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *RepoMappingMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RepoMappingMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown RepoMapping numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *RepoMappingMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(repomapping.FieldCreatedByEmail) {
		fields = append(fields, repomapping.FieldCreatedByEmail)
	}
	if m.FieldCleared(repomapping.FieldCreatedByName) {
		fields = append(fields, repomapping.FieldCreatedByName)
	}
	if m.FieldCleared(repomapping.FieldUpdatedByEmail) {
		fields = append(fields, repomapping.FieldUpdatedByEmail)
	}
	if m.FieldCleared(repomapping.FieldUpdatedByName) {
		fields = append(fields, repomapping.FieldUpdatedByName)
	}
	if m.FieldCleared(repomapping.FieldNotes) {
		fields = append(fields, repomapping.FieldNotes)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *RepoMappingMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *RepoMappingMutation) ClearField(name string) error {
	switch name {
	case repomapping.FieldCreatedByEmail:
		m.ClearCreatedByEmail()
		return nil
	case repomapping.FieldCreatedByName:
		m.ClearCreatedByName()
		return nil
	case repomapping.FieldUpdatedByEmail:
		m.ClearUpdatedByEmail()
		return nil
	case repomapping.FieldUpdatedByName:
		m.ClearUpdatedByName()
		return nil
	case repomapping.FieldNotes:
		m.ClearNotes()
		return nil
	}
	return fmt.Errorf("unknown RepoMapping nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *RepoMappingMutation) ResetField(name string) error {
	switch name {
	case repomapping.FieldSourceRel:
		m.ResetSourceRel()
		return nil
	case repomapping.FieldRepoURL:
		m.ResetRepoURL()
		return nil
	case repomapping.FieldTargetRel:
		m.ResetTargetRel()
		return nil
	case repomapping.FieldLinkName:
		m.ResetLinkName()
		return nil
	case repomapping.FieldKind:
		m.ResetKind()
		return nil
	case repomapping.FieldState:
		m.ResetState()
		return nil
	case repomapping.FieldCreatedByEmail:
		m.ResetCreatedByEmail()
		return nil
	case repomapping.FieldCreatedByName:
		m.ResetCreatedByName()
		return nil
	case repomapping.FieldUpdatedByEmail:
		m.ResetUpdatedByEmail()
		return nil
	case repomapping.FieldUpdatedByName:
		m.ResetUpdatedByName()
		return nil
	case repomapping.FieldNotes:
		m.ResetNotes()
		return nil
	case repomapping.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case repomapping.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown RepoMapping field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *RepoMappingMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *RepoMappingMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *RepoMappingMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *RepoMappingMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *RepoMappingMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *RepoMappingMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *RepoMappingMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown RepoMapping unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *RepoMappingMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown RepoMapping edge %s", name)
}

// RepoMetaMutation represents an operation that mutates the RepoMeta nodes in the graph.
type RepoMetaMutation struct {
	config
	op              Op
	typ             string
	id              *string
	private_repo_id *string
	display_name    *string
	created_at      *time.Time
	clearedFields   map[string]struct{}
	done            bool
	oldValue        func(context.Context) (*RepoMeta, error)
	predicates      []predicate.RepoMeta
}

var _ ent.Mutation = (*RepoMetaMutation)(nil)

// repometaOption allows management of the mutation configuration using functional options.
type repometaOption func(*RepoMetaMutation)

// newRepoMetaMutation creates new mutation for the RepoMeta entity.
func newRepoMetaMutation(c config, op Op, opts ...repometaOption) *RepoMetaMutation {
	m := &RepoMetaMutation{
		config:        c,
		op:            op,
		typ:           TypeRepoMeta,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withRepoMetaID sets the ID field of the mutation.
func withRepoMetaID(id string) repometaOption {
	return func(m *RepoMetaMutation) {
		var (
			err   error
			once  sync.Once
			value *RepoMeta
		)
		m.oldValue = func(ctx context.Context) (*RepoMeta, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().RepoMeta.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withRepoMeta sets the old RepoMeta of the mutation.
func withRepoMeta(node *RepoMeta) repometaOption {
	return func(m *RepoMetaMutation) {
		m.oldValue = func(context.Context) (*RepoMeta, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m RepoMetaMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m RepoMetaMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of RepoMeta entities.
func (m *RepoMetaMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *RepoMetaMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *RepoMetaMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().RepoMeta.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetPrivateRepoID sets the "private_repo_id" field.
func (m *RepoMetaMutation) SetPrivateRepoID(s string) {
	m.private_repo_id = &s
}

// PrivateRepoID returns the value of the "private_repo_id" field in the mutation.
func (m *RepoMetaMutation) PrivateRepoID() (r string, exists bool) {
	v := m.private_repo_id
	if v == nil {
		return
	}
	return *v, true
}

// OldPrivateRepoID returns the old "private_repo_id" field's value of the RepoMeta entity.
// If the RepoMeta object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepoMetaMutation) OldPrivateRepoID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPrivateRepoID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPrivateRepoID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPrivateRepoID: %w", err)
	}
	return oldValue.PrivateRepoID, nil
}

// ResetPrivateRepoID resets all changes to the "private_repo_id" field.
func (m *RepoMetaMutation) ResetPrivateRepoID() {
	m.private_repo_id = nil
}

// SetDisplayName sets the "display_name" field.
func (m *RepoMetaMutation) SetDisplayName(s string) {
	m.display_name = &s
}

// DisplayName returns the value of the "display_name" field in the mutation.
func (m *RepoMetaMutation) DisplayName() (r string, exists bool) {
	v := m.display_name
	if v == nil {
		return
	}
	return *v, true
}

// OldDisplayName returns the old "display_name" field's value of the RepoMeta entity.
// If the RepoMeta object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepoMetaMutation) OldDisplayName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDisplayName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDisplayName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDisplayName: %w", err)
	}
	return oldValue.DisplayName, nil
}

// ResetDisplayName resets all changes to the "display_name" field.
func (m *RepoMetaMutation) ResetDisplayName() {
	m.display_name = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *RepoMetaMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *RepoMetaMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the RepoMeta entity.
// If the RepoMeta object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepoMetaMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *RepoMetaMutation) ResetCreatedAt() {
	m.created_at = nil
}

// Where appends a list predicates to the RepoMetaMutation builder.
func (m *RepoMetaMutation) Where(ps ...predicate.RepoMeta) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the RepoMetaMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *RepoMetaMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.RepoMeta, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *RepoMetaMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *RepoMetaMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (RepoMeta).
func (m *RepoMetaMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *RepoMetaMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.private_repo_id != nil {
		fields = append(fields, repometa.FieldPrivateRepoID)
	}
	if m.display_name != nil {
		fields = append(fields, repometa.FieldDisplayName)
	}
	if m.created_at != nil {
		fields = append(fields, repometa.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *RepoMetaMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case repometa.FieldPrivateRepoID:
		return m.PrivateRepoID()
	case repometa.FieldDisplayName:
		return m.DisplayName()
	case repometa.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *RepoMetaMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case repometa.FieldPrivateRepoID:
		return m.OldPrivateRepoID(ctx)
	case repometa.FieldDisplayName:
		return m.OldDisplayName(ctx)
	case repometa.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown RepoMeta field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RepoMetaMutation) SetField(name string, value ent.Value) error {
	switch name {
	case repometa.FieldPrivateRepoID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPrivateRepoID(v)
		return nil
	case repometa.FieldDisplayName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDisplayName(v)
		return nil
	case repometa.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown RepoMeta field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *RepoMetaMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *RepoMetaMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RepoMetaMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown RepoMeta numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *RepoMetaMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *RepoMetaMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *RepoMetaMutation) ClearField(name string) error {
	return fmt.Errorf("unknown RepoMeta nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *RepoMetaMutation) ResetField(name string) error {
	switch name {
	case repometa.FieldPrivateRepoID:
		m.ResetPrivateRepoID()
		return nil
	case repometa.FieldDisplayName:
		m.ResetDisplayName()
		return nil
	case repometa.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown RepoMeta field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *RepoMetaMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *RepoMetaMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *RepoMetaMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *RepoMetaMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *RepoMetaMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *RepoMetaMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *RepoMetaMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown RepoMeta unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *RepoMetaMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown RepoMeta edge %s", name)
}

// RunLogMutation represents an operation that mutates the RunLog nodes in the graph.
type RunLogMutation struct {
	config
	op            Op
	typ           string
	id            *string
	profile_id    *string
	mapping_id    *string
	_op           *runlog.Op
	result        *runlog.Result
	user_email    *string
	user_name     *string
	message       *string
	created_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*RunLog, error)
	predicates    []predicate.RunLog
}

var _ ent.Mutation = (*RunLogMutation)(nil)

// runlogOption allows management of the mutation configuration using functional options.
type runlogOption func(*RunLogMutation)

// newRunLogMutation creates new mutation for the RunLog entity.
func newRunLogMutation(c config, op Op, opts ...runlogOption) *RunLogMutation {
	m := &RunLogMutation{
		config:        c,
		op:            op,
		typ:           TypeRunLog,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withRunLogID sets the ID field of the mutation.
func withRunLogID(id string) runlogOption {
	return func(m *RunLogMutation) {
		var (
			err   error
			once  sync.Once
			value *RunLog
		)
		m.oldValue = func(ctx context.Context) (*RunLog, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().RunLog.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withRunLog sets the old RunLog of the mutation.
func withRunLog(node *RunLog) runlogOption {
	return func(m *RunLogMutation) {
		m.oldValue = func(context.Context) (*RunLog, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m RunLogMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m RunLogMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of RunLog entities.
func (m *RunLogMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *RunLogMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *RunLogMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().RunLog.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetProfileID sets the "profile_id" field.
func (m *RunLogMutation) SetProfileID(s string) {
	m.profile_id = &s
}

// ProfileID returns the value of the "profile_id" field in the mutation.
func (m *RunLogMutation) ProfileID() (r string, exists bool) {
	v := m.profile_id
	if v == nil {
		return
	}
	return *v, true
}

// OldProfileID returns the old "profile_id" field's value of the RunLog entity.
// If the RunLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RunLogMutation) OldProfileID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProfileID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProfileID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProfileID: %w", err)
	}
	return oldValue.ProfileID, nil
}

// ResetProfileID resets all changes to the "profile_id" field.
func (m *RunLogMutation) ResetProfileID() {
	m.profile_id = nil
}

// SetMappingID sets the "mapping_id" field.
func (m *RunLogMutation) SetMappingID(s string) {
	m.mapping_id = &s
}

// MappingID returns the value of the "mapping_id" field in the mutation.
func (m *RunLogMutation) MappingID() (r string, exists bool) {
	v := m.mapping_id
	if v == nil {
		return
	}
	return *v, true
}

// OldMappingID returns the old "mapping_id" field's value of the RunLog entity.
// If the RunLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RunLogMutation) OldMappingID(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMappingID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMappingID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMappingID: %w", err)
	}
	return oldValue.MappingID, nil
}

// ClearMappingID clears the value of the "mapping_id" field.
func (m *RunLogMutation) ClearMappingID() {
	m.mapping_id = nil
	m.clearedFields[runlog.FieldMappingID] = struct{}{}
}

// MappingIDCleared returns if the "mapping_id" field was cleared in this mutation.
func (m *RunLogMutation) MappingIDCleared() bool {
	_, ok := m.clearedFields[runlog.FieldMappingID]
	return ok
}

// ResetMappingID resets all changes to the "mapping_id" field.
func (m *RunLogMutation) ResetMappingID() {
	m.mapping_id = nil
	delete(m.clearedFields, runlog.FieldMappingID)
}

// SetOpField sets the "op" field.
func (m *RunLogMutation) SetOpField(r runlog.Op) {
	m._op = &r
}

// GetOp returns the value of the "op" field in the mutation.
func (m *RunLogMutation) GetOp() (r runlog.Op, exists bool) {
	v := m._op
	if v == nil {
		return
	}
	return *v, true
}

// OldOp returns the old "op" field's value of the RunLog entity.
// If the RunLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RunLogMutation) OldOp(ctx context.Context) (v runlog.Op, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOp is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOp requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOp: %w", err)
	}
	return oldValue.Op, nil
}

// ResetOp resets all changes to the "op" field.
func (m *RunLogMutation) ResetOp() {
	m._op = nil
}

// SetResult sets the "result" field.
func (m *RunLogMutation) SetResult(r runlog.Result) {
	m.result = &r
}

// Result returns the value of the "result" field in the mutation.
func (m *RunLogMutation) Result() (r runlog.Result, exists bool) {
	v := m.result
	if v == nil {
		return
	}
	return *v, true
}

// OldResult returns the old "result" field's value of the RunLog entity.
// If the RunLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RunLogMutation) OldResult(ctx context.Context) (v runlog.Result, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldResult is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldResult requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldResult: %w", err)
	}
	return oldValue.Result, nil
}

// ResetResult resets all changes to the "result" field.
func (m *RunLogMutation) ResetResult() {
	m.result = nil
}

// SetUserEmail sets the "user_email" field.
func (m *RunLogMutation) SetUserEmail(s string) {
	m.user_email = &s
}

// UserEmail returns the value of the "user_email" field in the mutation.
func (m *RunLogMutation) UserEmail() (r string, exists bool) {
	v := m.user_email
	if v == nil {
		return
	}
	return *v, true
}

// OldUserEmail returns the old "user_email" field's value of the RunLog entity.
// If the RunLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RunLogMutation) OldUserEmail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserEmail is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserEmail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserEmail: %w", err)
	}
	return oldValue.UserEmail, nil
}

// ClearUserEmail clears the value of the "user_email" field.
func (m *RunLogMutation) ClearUserEmail() {
	m.user_email = nil
	m.clearedFields[runlog.FieldUserEmail] = struct{}{}
}

// UserEmailCleared returns if the "user_email" field was cleared in this mutation.
func (m *RunLogMutation) UserEmailCleared() bool {
	_, ok := m.clearedFields[runlog.FieldUserEmail]
	return ok
}

// ResetUserEmail resets all changes to the "user_email" field.
func (m *RunLogMutation) ResetUserEmail() {
	m.user_email = nil
	delete(m.clearedFields, runlog.FieldUserEmail)
}

// SetUserName sets the "user_name" field.
func (m *RunLogMutation) SetUserName(s string) {
	m.user_name = &s
}

// UserName returns the value of the "user_name" field in the mutation.
func (m *RunLogMutation) UserName() (r string, exists bool) {
	v := m.user_name
	if v == nil {
		return
	}
	return *v, true
}

// OldUserName returns the old "user_name" field's value of the RunLog entity.
// If the RunLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RunLogMutation) OldUserName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserName: %w", err)
	}
	return oldValue.UserName, nil
}

// ClearUserName clears the value of the "user_name" field.
func (m *RunLogMutation) ClearUserName() {
	m.user_name = nil
	m.clearedFields[runlog.FieldUserName] = struct{}{}
}

// UserNameCleared returns if the "user_name" field was cleared in this mutation.
func (m *RunLogMutation) UserNameCleared() bool {
	_, ok := m.clearedFields[runlog.FieldUserName]
	return ok
}

// ResetUserName resets all changes to the "user_name" field.
func (m *RunLogMutation) ResetUserName() {
	m.user_name = nil
	delete(m.clearedFields, runlog.FieldUserName)
}

// SetMessage sets the "message" field.
func (m *RunLogMutation) SetMessage(s string) {
	m.message = &s
}

// Message returns the value of the "message" field in the mutation.
func (m *RunLogMutation) Message() (r string, exists bool) {
	v := m.message
	if v == nil {
		return
	}
	return *v, true
}

// OldMessage returns the old "message" field's value of the RunLog entity.
// If the RunLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RunLogMutation) OldMessage(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMessage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMessage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMessage: %w", err)
	}
	return oldValue.Message, nil
}

// ClearMessage clears the value of the "message" field.
func (m *RunLogMutation) ClearMessage() {
	m.message = nil
	m.clearedFields[runlog.FieldMessage] = struct{}{}
}

// MessageCleared returns if the "message" field was cleared in this mutation.
func (m *RunLogMutation) MessageCleared() bool {
	_, ok := m.clearedFields[runlog.FieldMessage]
	return ok
}

// ResetMessage resets all changes to the "message" field.
func (m *RunLogMutation) ResetMessage() {
	m.message = nil
	delete(m.clearedFields, runlog.FieldMessage)
}

// SetCreatedAt sets the "created_at" field.
func (m *RunLogMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *RunLogMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the RunLog entity.
// If the RunLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RunLogMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *RunLogMutation) ResetCreatedAt() {
	m.created_at = nil
}

// Where appends a list predicates to the RunLogMutation builder.
func (m *RunLogMutation) Where(ps ...predicate.RunLog) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the RunLogMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *RunLogMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.RunLog, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *RunLogMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *RunLogMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (RunLog).
func (m *RunLogMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *RunLogMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.profile_id != nil {
		fields = append(fields, runlog.FieldProfileID)
	}
	if m.mapping_id != nil {
		fields = append(fields, runlog.FieldMappingID)
	}
	if m._op != nil {
		fields = append(fields, runlog.FieldOp)
	}
	if m.result != nil {
		fields = append(fields, runlog.FieldResult)
	}
	if m.user_email != nil {
		fields = append(fields, runlog.FieldUserEmail)
	}
	if m.user_name != nil {
		fields = append(fields, runlog.FieldUserName)
	}
	if m.message != nil {
		fields = append(fields, runlog.FieldMessage)
	}
	if m.created_at != nil {
		fields = append(fields, runlog.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *RunLogMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case runlog.FieldProfileID:
		return m.ProfileID()
	case runlog.FieldMappingID:
		return m.MappingID()
	case runlog.FieldOp:
		return m.GetOp()
	case runlog.FieldResult:
		return m.Result()
	case runlog.FieldUserEmail:
		return m.UserEmail()
	case runlog.FieldUserName:
		return m.UserName()
	case runlog.FieldMessage:
		return m.Message()
	case runlog.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *RunLogMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case runlog.FieldProfileID:
		return m.OldProfileID(ctx)
	case runlog.FieldMappingID:
		return m.OldMappingID(ctx)
	case runlog.FieldOp:
		return m.OldOp(ctx)
	case runlog.FieldResult:
		return m.OldResult(ctx)
	case runlog.FieldUserEmail:
		return m.OldUserEmail(ctx)
	case runlog.FieldUserName:
		return m.OldUserName(ctx)
	case runlog.FieldMessage:
		return m.OldMessage(ctx)
	case runlog.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown RunLog field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RunLogMutation) SetField(name string, value ent.Value) error {
	switch name {
	case runlog.FieldProfileID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProfileID(v)
		return nil
	case runlog.FieldMappingID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMappingID(v)
		return nil
	case runlog.FieldOp:
		v, ok := value.(runlog.Op)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOpField(v)
		return nil
	case runlog.FieldResult:
		v, ok := value.(runlog.Result)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetResult(v)
		return nil
	case runlog.FieldUserEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserEmail(v)
		return nil
	case runlog.FieldUserName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserName(v)
		return nil
	case runlog.FieldMessage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMessage(v)
		return nil
	case runlog.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown RunLog field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *RunLogMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *RunLogMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RunLogMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown RunLog numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *RunLogMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(runlog.FieldMappingID) {
		fields = append(fields, runlog.FieldMappingID)
	}
	if m.FieldCleared(runlog.FieldUserEmail) {
		fields = append(fields, runlog.FieldUserEmail)
	}
	if m.FieldCleared(runlog.FieldUserName) {
		fields = append(fields, runlog.FieldUserName)
	}
	if m.FieldCleared(runlog.FieldMessage) {
		fields = append(fields, runlog.FieldMessage)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *RunLogMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *RunLogMutation) ClearField(name string) error {
	switch name {
	case runlog.FieldMappingID:
		m.ClearMappingID()
		return nil
	case runlog.FieldUserEmail:
		m.ClearUserEmail()
		return nil
	case runlog.FieldUserName:
		m.ClearUserName()
		return nil
	case runlog.FieldMessage:
		m.ClearMessage()
		return nil
	}
	return fmt.Errorf("unknown RunLog nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *RunLogMutation) ResetField(name string) error {
	switch name {
	case runlog.FieldProfileID:
		m.ResetProfileID()
		return nil
	case runlog.FieldMappingID:
		m.ResetMappingID()
		return nil
	case runlog.FieldOp:
		m.ResetOp()
		return nil
	case runlog.FieldResult:
		m.ResetResult()
		return nil
	case runlog.FieldUserEmail:
		m.ResetUserEmail()
		return nil
	case runlog.FieldUserName:
		m.ResetUserName()
		return nil
	case runlog.FieldMessage:
		m.ResetMessage()
		return nil
	case runlog.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown RunLog field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *RunLogMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *RunLogMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *RunLogMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *RunLogMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *RunLogMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *RunLogMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *RunLogMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown RunLog unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *RunLogMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown RunLog edge %s", name)
}
