// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/khanakia/repolink-go/internal/ent/repomapping"
)

// RepoMapping is the model entity for the RepoMapping schema.
type RepoMapping struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// path relative to the private-repo root; e.g. markdown-viewer-chrome-ext
	SourceRel string `json:"source_rel,omitempty"`
	// canonical consumer repo URL; e.g. github.com/khanakia/abc
	RepoURL string `json:"repo_url,omitempty"`
	// relative dir inside the consumer repo; e.g. research (empty = repo root)
	TargetRel string `json:"target_rel,omitempty"`
	// filename of the symlink inside target_rel
	LinkName string `json:"link_name,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind repomapping.Kind `json:"kind,omitempty"`
	// State holds the value of the "state" field.
	State repomapping.State `json:"state,omitempty"`
	// CreatedByEmail holds the value of the "created_by_email" field.
	CreatedByEmail string `json:"created_by_email,omitempty"`
	// CreatedByName holds the value of the "created_by_name" field.
	CreatedByName string `json:"created_by_name,omitempty"`
	// UpdatedByEmail holds the value of the "updated_by_email" field.
	UpdatedByEmail string `json:"updated_by_email,omitempty"`
	// UpdatedByName holds the value of the "updated_by_name" field.
	UpdatedByName string `json:"updated_by_name,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RepoMapping) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case repomapping.FieldID, repomapping.FieldSourceRel, repomapping.FieldRepoURL, repomapping.FieldTargetRel, repomapping.FieldLinkName, repomapping.FieldKind, repomapping.FieldState, repomapping.FieldCreatedByEmail, repomapping.FieldCreatedByName, repomapping.FieldUpdatedByEmail, repomapping.FieldUpdatedByName, repomapping.FieldNotes:
			values[i] = new(sql.NullString)
		case repomapping.FieldCreatedAt, repomapping.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RepoMapping fields.
func (_m *RepoMapping) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case repomapping.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case repomapping.FieldSourceRel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_rel", values[i])
			} else if value.Valid {
				_m.SourceRel = value.String
			}
		case repomapping.FieldRepoURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repo_url", values[i])
			} else if value.Valid {
				_m.RepoURL = value.String
			}
		case repomapping.FieldTargetRel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_rel", values[i])
			} else if value.Valid {
				_m.TargetRel = value.String
			}
		case repomapping.FieldLinkName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field link_name", values[i])
			} else if value.Valid {
				_m.LinkName = value.String
			}
		case repomapping.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = repomapping.Kind(value.String)
			}
		case repomapping.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = repomapping.State(value.String)
			}
		case repomapping.FieldCreatedByEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_email", values[i])
			} else if value.Valid {
				_m.CreatedByEmail = value.String
			}
		case repomapping.FieldCreatedByName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_name", values[i])
			} else if value.Valid {
				_m.CreatedByName = value.String
			}
		case repomapping.FieldUpdatedByEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by_email", values[i])
			} else if value.Valid {
				_m.UpdatedByEmail = value.String
			}
		case repomapping.FieldUpdatedByName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by_name", values[i])
			} else if value.Valid {
				_m.UpdatedByName = value.String
			}
		case repomapping.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case repomapping.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case repomapping.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RepoMapping.
// This includes values selected through modifiers, order, etc.
func (_m *RepoMapping) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RepoMapping.
// Note that you need to call RepoMapping.Unwrap() before calling this method if this RepoMapping
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RepoMapping) Update() *RepoMappingUpdateOne {
	return NewRepoMappingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RepoMapping entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RepoMapping) Unwrap() *RepoMapping {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RepoMapping is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RepoMapping) String() string {
	var builder strings.Builder
	builder.WriteString("RepoMapping(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("source_rel=")
	builder.WriteString(_m.SourceRel)
	builder.WriteString(", ")
	builder.WriteString("repo_url=")
	builder.WriteString(_m.RepoURL)
	builder.WriteString(", ")
	builder.WriteString("target_rel=")
	builder.WriteString(_m.TargetRel)
	builder.WriteString(", ")
	builder.WriteString("link_name=")
	builder.WriteString(_m.LinkName)
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.Kind))
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", _m.State))
	builder.WriteString(", ")
	builder.WriteString("created_by_email=")
	builder.WriteString(_m.CreatedByEmail)
	builder.WriteString(", ")
	builder.WriteString("created_by_name=")
	builder.WriteString(_m.CreatedByName)
	builder.WriteString(", ")
	builder.WriteString("updated_by_email=")
	builder.WriteString(_m.UpdatedByEmail)
	builder.WriteString(", ")
	builder.WriteString("updated_by_name=")
	builder.WriteString(_m.UpdatedByName)
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RepoMappings is a parsable slice of RepoMapping.
type RepoMappings []*RepoMapping
