// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/khanakia/repolink-go/internal/ent/repomapping"
)

// RepoMappingCreate is the builder for creating a RepoMapping entity.
type RepoMappingCreate struct {
	config
	mutation *RepoMappingMutation
	hooks    []Hook
}

// SetSourceRel sets the "source_rel" field.
func (_c *RepoMappingCreate) SetSourceRel(v string) *RepoMappingCreate {
	_c.mutation.SetSourceRel(v)
	return _c
}

// SetRepoURL sets the "repo_url" field.
func (_c *RepoMappingCreate) SetRepoURL(v string) *RepoMappingCreate {
	_c.mutation.SetRepoURL(v)
	return _c
}

// SetTargetRel sets the "target_rel" field.
func (_c *RepoMappingCreate) SetTargetRel(v string) *RepoMappingCreate {
	_c.mutation.SetTargetRel(v)
	return _c
}

// SetLinkName sets the "link_name" field.
func (_c *RepoMappingCreate) SetLinkName(v string) *RepoMappingCreate {
	_c.mutation.SetLinkName(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *RepoMappingCreate) SetKind(v repomapping.Kind) *RepoMappingCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *RepoMappingCreate) SetNillableKind(v *repomapping.Kind) *RepoMappingCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *RepoMappingCreate) SetState(v repomapping.State) *RepoMappingCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *RepoMappingCreate) SetNillableState(v *repomapping.State) *RepoMappingCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetCreatedByEmail sets the "created_by_email" field.
func (_c *RepoMappingCreate) SetCreatedByEmail(v string) *RepoMappingCreate {
	_c.mutation.SetCreatedByEmail(v)
	return _c
}

// SetNillableCreatedByEmail sets the "created_by_email" field if the given value is not nil.
func (_c *RepoMappingCreate) SetNillableCreatedByEmail(v *string) *RepoMappingCreate {
	if v != nil {
		_c.SetCreatedByEmail(*v)
	}
	return _c
}

// SetCreatedByName sets the "created_by_name" field.
func (_c *RepoMappingCreate) SetCreatedByName(v string) *RepoMappingCreate {
	_c.mutation.SetCreatedByName(v)
	return _c
}

// SetNillableCreatedByName sets the "created_by_name" field if the given value is not nil.
func (_c *RepoMappingCreate) SetNillableCreatedByName(v *string) *RepoMappingCreate {
	if v != nil {
		_c.SetCreatedByName(*v)
	}
	return _c
}

// SetUpdatedByEmail sets the "updated_by_email" field.
func (_c *RepoMappingCreate) SetUpdatedByEmail(v string) *RepoMappingCreate {
	_c.mutation.SetUpdatedByEmail(v)
	return _c
}

// SetNillableUpdatedByEmail sets the "updated_by_email" field if the given value is not nil.
func (_c *RepoMappingCreate) SetNillableUpdatedByEmail(v *string) *RepoMappingCreate {
	if v != nil {
		_c.SetUpdatedByEmail(*v)
	}
	return _c
}

// SetUpdatedByName sets the "updated_by_name" field.
func (_c *RepoMappingCreate) SetUpdatedByName(v string) *RepoMappingCreate {
	_c.mutation.SetUpdatedByName(v)
	return _c
}

// SetNillableUpdatedByName sets the "updated_by_name" field if the given value is not nil.
func (_c *RepoMappingCreate) SetNillableUpdatedByName(v *string) *RepoMappingCreate {
	if v != nil {
		_c.SetUpdatedByName(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *RepoMappingCreate) SetNotes(v string) *RepoMappingCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *RepoMappingCreate) SetNillableNotes(v *string) *RepoMappingCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RepoMappingCreate) SetCreatedAt(v time.Time) *RepoMappingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RepoMappingCreate) SetNillableCreatedAt(v *time.Time) *RepoMappingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RepoMappingCreate) SetUpdatedAt(v time.Time) *RepoMappingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RepoMappingCreate) SetNillableUpdatedAt(v *time.Time) *RepoMappingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RepoMappingCreate) SetID(v string) *RepoMappingCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RepoMappingCreate) SetNillableID(v *string) *RepoMappingCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the RepoMappingMutation object of the builder.
func (_c *RepoMappingCreate) Mutation() *RepoMappingMutation {
	return _c.mutation
}

// Save creates the RepoMapping in the database.
func (_c *RepoMappingCreate) Save(ctx context.Context) (*RepoMapping, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RepoMappingCreate) SaveX(ctx context.Context) *RepoMapping {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RepoMappingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RepoMappingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RepoMappingCreate) defaults() {
	if _, ok := _c.mutation.Kind(); !ok {
		v := repomapping.DefaultKind
		_c.mutation.SetKind(v)
	}
	if _, ok := _c.mutation.State(); !ok {
		v := repomapping.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := repomapping.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := repomapping.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := repomapping.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RepoMappingCreate) check() error {
	if _, ok := _c.mutation.SourceRel(); !ok {
		return &ValidationError{Name: "source_rel", err: errors.New(`ent: missing required field "RepoMapping.source_rel"`)}
	}
	if v, ok := _c.mutation.SourceRel(); ok {
		if err := repomapping.SourceRelValidator(v); err != nil {
			return &ValidationError{Name: "source_rel", err: fmt.Errorf(`ent: validator failed for field "RepoMapping.source_rel": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RepoURL(); !ok {
		return &ValidationError{Name: "repo_url", err: errors.New(`ent: missing required field "RepoMapping.repo_url"`)}
	}
	if v, ok := _c.mutation.RepoURL(); ok {
		if err := repomapping.RepoURLValidator(v); err != nil {
			return &ValidationError{Name: "repo_url", err: fmt.Errorf(`ent: validator failed for field "RepoMapping.repo_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TargetRel(); !ok {
		return &ValidationError{Name: "target_rel", err: errors.New(`ent: missing required field "RepoMapping.target_rel"`)}
	}
	if _, ok := _c.mutation.LinkName(); !ok {
		return &ValidationError{Name: "link_name", err: errors.New(`ent: missing required field "RepoMapping.link_name"`)}
	}
	if v, ok := _c.mutation.LinkName(); ok {
		if err := repomapping.LinkNameValidator(v); err != nil {
			return &ValidationError{Name: "link_name", err: fmt.Errorf(`ent: validator failed for field "RepoMapping.link_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "RepoMapping.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := repomapping.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "RepoMapping.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "RepoMapping.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := repomapping.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "RepoMapping.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RepoMapping.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RepoMapping.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := repomapping.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "RepoMapping.id": %w`, err)}
		}
	}
	return nil
}

func (_c *RepoMappingCreate) sqlSave(ctx context.Context) (*RepoMapping, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected RepoMapping.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RepoMappingCreate) createSpec() (*RepoMapping, *sqlgraph.CreateSpec) {
	var (
		_node = &RepoMapping{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(repomapping.Table, sqlgraph.NewFieldSpec(repomapping.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.SourceRel(); ok {
		_spec.SetField(repomapping.FieldSourceRel, field.TypeString, value)
		_node.SourceRel = value
	}
	if value, ok := _c.mutation.RepoURL(); ok {
		_spec.SetField(repomapping.FieldRepoURL, field.TypeString, value)
		_node.RepoURL = value
	}
	if value, ok := _c.mutation.TargetRel(); ok {
		_spec.SetField(repomapping.FieldTargetRel, field.TypeString, value)
		_node.TargetRel = value
	}
	if value, ok := _c.mutation.LinkName(); ok {
		_spec.SetField(repomapping.FieldLinkName, field.TypeString, value)
		_node.LinkName = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(repomapping.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(repomapping.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := _c.mutation.CreatedByEmail(); ok {
		_spec.SetField(repomapping.FieldCreatedByEmail, field.TypeString, value)
		_node.CreatedByEmail = value
	}
	if value, ok := _c.mutation.CreatedByName(); ok {
		_spec.SetField(repomapping.FieldCreatedByName, field.TypeString, value)
		_node.CreatedByName = value
	}
	if value, ok := _c.mutation.UpdatedByEmail(); ok {
		_spec.SetField(repomapping.FieldUpdatedByEmail, field.TypeString, value)
		_node.UpdatedByEmail = value
	}
	if value, ok := _c.mutation.UpdatedByName(); ok {
		_spec.SetField(repomapping.FieldUpdatedByName, field.TypeString, value)
		_node.UpdatedByName = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(repomapping.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(repomapping.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(repomapping.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// RepoMappingCreateBulk is the builder for creating many RepoMapping entities in bulk.
type RepoMappingCreateBulk struct {
	config
	err      error
	builders []*RepoMappingCreate
}

// Save creates the RepoMapping entities in the database.
func (_c *RepoMappingCreateBulk) Save(ctx context.Context) ([]*RepoMapping, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RepoMapping, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RepoMappingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RepoMappingCreateBulk) SaveX(ctx context.Context) []*RepoMapping {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RepoMappingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RepoMappingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
