// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/khanakia/repolink-go/internal/ent/predicate"
	"github.com/khanakia/repolink-go/internal/ent/repometa"
)

// RepoMetaUpdate is the builder for updating RepoMeta entities.
type RepoMetaUpdate struct {
	config
	hooks    []Hook
	mutation *RepoMetaMutation
}

// Where appends a list predicates to the RepoMetaUpdate builder.
func (_u *RepoMetaUpdate) Where(ps ...predicate.RepoMeta) *RepoMetaUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *RepoMetaUpdate) SetDisplayName(v string) *RepoMetaUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *RepoMetaUpdate) SetNillableDisplayName(v *string) *RepoMetaUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// Mutation returns the RepoMetaMutation object of the builder.
func (_u *RepoMetaUpdate) Mutation() *RepoMetaMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RepoMetaUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RepoMetaUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RepoMetaUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RepoMetaUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RepoMetaUpdate) check() error {
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := repometa.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "RepoMeta.display_name": %w`, err)}
		}
	}
	return nil
}

func (_u *RepoMetaUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(repometa.Table, repometa.Columns, sqlgraph.NewFieldSpec(repometa.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(repometa.FieldDisplayName, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repometa.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RepoMetaUpdateOne is the builder for updating a single RepoMeta entity.
type RepoMetaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RepoMetaMutation
}

// SetDisplayName sets the "display_name" field.
func (_u *RepoMetaUpdateOne) SetDisplayName(v string) *RepoMetaUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *RepoMetaUpdateOne) SetNillableDisplayName(v *string) *RepoMetaUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// Mutation returns the RepoMetaMutation object of the builder.
func (_u *RepoMetaUpdateOne) Mutation() *RepoMetaMutation {
	return _u.mutation
}

// Where appends a list predicates to the RepoMetaUpdate builder.
func (_u *RepoMetaUpdateOne) Where(ps ...predicate.RepoMeta) *RepoMetaUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RepoMetaUpdateOne) Select(field string, fields ...string) *RepoMetaUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RepoMeta entity.
func (_u *RepoMetaUpdateOne) Save(ctx context.Context) (*RepoMeta, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RepoMetaUpdateOne) SaveX(ctx context.Context) *RepoMeta {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RepoMetaUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RepoMetaUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RepoMetaUpdateOne) check() error {
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := repometa.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "RepoMeta.display_name": %w`, err)}
		}
	}
	return nil
}

func (_u *RepoMetaUpdateOne) sqlSave(ctx context.Context) (_node *RepoMeta, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(repometa.Table, repometa.Columns, sqlgraph.NewFieldSpec(repometa.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RepoMeta.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, repometa.FieldID)
		for _, f := range fields {
			if !repometa.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != repometa.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(repometa.FieldDisplayName, field.TypeString, value)
	}
	_node = &RepoMeta{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repometa.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
