// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/khanakia/repolink-go/internal/ent/predicate"
	"github.com/khanakia/repolink-go/internal/ent/repomapping"
)

// RepoMappingUpdate is the builder for updating RepoMapping entities.
type RepoMappingUpdate struct {
	config
	hooks    []Hook
	mutation *RepoMappingMutation
}

// Where appends a list predicates to the RepoMappingUpdate builder.
func (_u *RepoMappingUpdate) Where(ps ...predicate.RepoMapping) *RepoMappingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSourceRel sets the "source_rel" field.
func (_u *RepoMappingUpdate) SetSourceRel(v string) *RepoMappingUpdate {
	_u.mutation.SetSourceRel(v)
	return _u
}

// SetNillableSourceRel sets the "source_rel" field if the given value is not nil.
func (_u *RepoMappingUpdate) SetNillableSourceRel(v *string) *RepoMappingUpdate {
	if v != nil {
		_u.SetSourceRel(*v)
	}
	return _u
}

// SetRepoURL sets the "repo_url" field.
func (_u *RepoMappingUpdate) SetRepoURL(v string) *RepoMappingUpdate {
	_u.mutation.SetRepoURL(v)
	return _u
}

// SetNillableRepoURL sets the "repo_url" field if the given value is not nil.
func (_u *RepoMappingUpdate) SetNillableRepoURL(v *string) *RepoMappingUpdate {
	if v != nil {
		_u.SetRepoURL(*v)
	}
	return _u
}

// SetTargetRel sets the "target_rel" field.
func (_u *RepoMappingUpdate) SetTargetRel(v string) *RepoMappingUpdate {
	_u.mutation.SetTargetRel(v)
	return _u
}

// SetNillableTargetRel sets the "target_rel" field if the given value is not nil.
func (_u *RepoMappingUpdate) SetNillableTargetRel(v *string) *RepoMappingUpdate {
	if v != nil {
		_u.SetTargetRel(*v)
	}
	return _u
}

// SetLinkName sets the "link_name" field.
func (_u *RepoMappingUpdate) SetLinkName(v string) *RepoMappingUpdate {
	_u.mutation.SetLinkName(v)
	return _u
}

// SetNillableLinkName sets the "link_name" field if the given value is not nil.
func (_u *RepoMappingUpdate) SetNillableLinkName(v *string) *RepoMappingUpdate {
	if v != nil {
		_u.SetLinkName(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *RepoMappingUpdate) SetKind(v repomapping.Kind) *RepoMappingUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *RepoMappingUpdate) SetNillableKind(v *repomapping.Kind) *RepoMappingUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *RepoMappingUpdate) SetState(v repomapping.State) *RepoMappingUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *RepoMappingUpdate) SetNillableState(v *repomapping.State) *RepoMappingUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetCreatedByEmail sets the "created_by_email" field.
func (_u *RepoMappingUpdate) SetCreatedByEmail(v string) *RepoMappingUpdate {
	_u.mutation.SetCreatedByEmail(v)
	return _u
}

// SetNillableCreatedByEmail sets the "created_by_email" field if the given value is not nil.
func (_u *RepoMappingUpdate) SetNillableCreatedByEmail(v *string) *RepoMappingUpdate {
	if v != nil {
		_u.SetCreatedByEmail(*v)
	}
	return _u
}

// ClearCreatedByEmail clears the value of the "created_by_email" field.
func (_u *RepoMappingUpdate) ClearCreatedByEmail() *RepoMappingUpdate {
	_u.mutation.ClearCreatedByEmail()
	return _u
}

// SetCreatedByName sets the "created_by_name" field.
func (_u *RepoMappingUpdate) SetCreatedByName(v string) *RepoMappingUpdate {
	_u.mutation.SetCreatedByName(v)
	return _u
}

// SetNillableCreatedByName sets the "created_by_name" field if the given value is not nil.
func (_u *RepoMappingUpdate) SetNillableCreatedByName(v *string) *RepoMappingUpdate {
	if v != nil {
		_u.SetCreatedByName(*v)
	}
	return _u
}

// ClearCreatedByName clears the value of the "created_by_name" field.
func (_u *RepoMappingUpdate) ClearCreatedByName() *RepoMappingUpdate {
	_u.mutation.ClearCreatedByName()
	return _u
}

// SetUpdatedByEmail sets the "updated_by_email" field.
func (_u *RepoMappingUpdate) SetUpdatedByEmail(v string) *RepoMappingUpdate {
	_u.mutation.SetUpdatedByEmail(v)
	return _u
}

// SetNillableUpdatedByEmail sets the "updated_by_email" field if the given value is not nil.
func (_u *RepoMappingUpdate) SetNillableUpdatedByEmail(v *string) *RepoMappingUpdate {
	if v != nil {
		_u.SetUpdatedByEmail(*v)
	}
	return _u
}

// ClearUpdatedByEmail clears the value of the "updated_by_email" field.
func (_u *RepoMappingUpdate) ClearUpdatedByEmail() *RepoMappingUpdate {
	_u.mutation.ClearUpdatedByEmail()
	return _u
}

// SetUpdatedByName sets the "updated_by_name" field.
func (_u *RepoMappingUpdate) SetUpdatedByName(v string) *RepoMappingUpdate {
	_u.mutation.SetUpdatedByName(v)
	return _u
}

// SetNillableUpdatedByName sets the "updated_by_name" field if the given value is not nil.
func (_u *RepoMappingUpdate) SetNillableUpdatedByName(v *string) *RepoMappingUpdate {
	if v != nil {
		_u.SetUpdatedByName(*v)
	}
	return _u
}

// ClearUpdatedByName clears the value of the "updated_by_name" field.
func (_u *RepoMappingUpdate) ClearUpdatedByName() *RepoMappingUpdate {
	_u.mutation.ClearUpdatedByName()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *RepoMappingUpdate) SetNotes(v string) *RepoMappingUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *RepoMappingUpdate) SetNillableNotes(v *string) *RepoMappingUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *RepoMappingUpdate) ClearNotes() *RepoMappingUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RepoMappingUpdate) SetUpdatedAt(v time.Time) *RepoMappingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the RepoMappingMutation object of the builder.
func (_u *RepoMappingUpdate) Mutation() *RepoMappingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RepoMappingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RepoMappingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RepoMappingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RepoMappingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RepoMappingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := repomapping.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RepoMappingUpdate) check() error {
	if v, ok := _u.mutation.SourceRel(); ok {
		if err := repomapping.SourceRelValidator(v); err != nil {
			return &ValidationError{Name: "source_rel", err: fmt.Errorf(`ent: validator failed for field "RepoMapping.source_rel": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RepoURL(); ok {
		if err := repomapping.RepoURLValidator(v); err != nil {
			return &ValidationError{Name: "repo_url", err: fmt.Errorf(`ent: validator failed for field "RepoMapping.repo_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LinkName(); ok {
		if err := repomapping.LinkNameValidator(v); err != nil {
			return &ValidationError{Name: "link_name", err: fmt.Errorf(`ent: validator failed for field "RepoMapping.link_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := repomapping.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "RepoMapping.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := repomapping.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "RepoMapping.state": %w`, err)}
		}
	}
	return nil
}

func (_u *RepoMappingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(repomapping.Table, repomapping.Columns, sqlgraph.NewFieldSpec(repomapping.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceRel(); ok {
		_spec.SetField(repomapping.FieldSourceRel, field.TypeString, value)
	}
	if value, ok := _u.mutation.RepoURL(); ok {
		_spec.SetField(repomapping.FieldRepoURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetRel(); ok {
		_spec.SetField(repomapping.FieldTargetRel, field.TypeString, value)
	}
	if value, ok := _u.mutation.LinkName(); ok {
		_spec.SetField(repomapping.FieldLinkName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(repomapping.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(repomapping.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CreatedByEmail(); ok {
		_spec.SetField(repomapping.FieldCreatedByEmail, field.TypeString, value)
	}
	if _u.mutation.CreatedByEmailCleared() {
		_spec.ClearField(repomapping.FieldCreatedByEmail, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedByName(); ok {
		_spec.SetField(repomapping.FieldCreatedByName, field.TypeString, value)
	}
	if _u.mutation.CreatedByNameCleared() {
		_spec.ClearField(repomapping.FieldCreatedByName, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedByEmail(); ok {
		_spec.SetField(repomapping.FieldUpdatedByEmail, field.TypeString, value)
	}
	if _u.mutation.UpdatedByEmailCleared() {
		_spec.ClearField(repomapping.FieldUpdatedByEmail, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedByName(); ok {
		_spec.SetField(repomapping.FieldUpdatedByName, field.TypeString, value)
	}
	if _u.mutation.UpdatedByNameCleared() {
		_spec.ClearField(repomapping.FieldUpdatedByName, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(repomapping.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(repomapping.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(repomapping.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repomapping.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RepoMappingUpdateOne is the builder for updating a single RepoMapping entity.
type RepoMappingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RepoMappingMutation
}

// SetSourceRel sets the "source_rel" field.
func (_u *RepoMappingUpdateOne) SetSourceRel(v string) *RepoMappingUpdateOne {
	_u.mutation.SetSourceRel(v)
	return _u
}

// SetNillableSourceRel sets the "source_rel" field if the given value is not nil.
func (_u *RepoMappingUpdateOne) SetNillableSourceRel(v *string) *RepoMappingUpdateOne {
	if v != nil {
		_u.SetSourceRel(*v)
	}
	return _u
}

// SetRepoURL sets the "repo_url" field.
func (_u *RepoMappingUpdateOne) SetRepoURL(v string) *RepoMappingUpdateOne {
	_u.mutation.SetRepoURL(v)
	return _u
}

// SetNillableRepoURL sets the "repo_url" field if the given value is not nil.
func (_u *RepoMappingUpdateOne) SetNillableRepoURL(v *string) *RepoMappingUpdateOne {
	if v != nil {
		_u.SetRepoURL(*v)
	}
	return _u
}

// SetTargetRel sets the "target_rel" field.
func (_u *RepoMappingUpdateOne) SetTargetRel(v string) *RepoMappingUpdateOne {
	_u.mutation.SetTargetRel(v)
	return _u
}

// SetNillableTargetRel sets the "target_rel" field if the given value is not nil.
func (_u *RepoMappingUpdateOne) SetNillableTargetRel(v *string) *RepoMappingUpdateOne {
	if v != nil {
		_u.SetTargetRel(*v)
	}
	return _u
}

// SetLinkName sets the "link_name" field.
func (_u *RepoMappingUpdateOne) SetLinkName(v string) *RepoMappingUpdateOne {
	_u.mutation.SetLinkName(v)
	return _u
}

// SetNillableLinkName sets the "link_name" field if the given value is not nil.
func (_u *RepoMappingUpdateOne) SetNillableLinkName(v *string) *RepoMappingUpdateOne {
	if v != nil {
		_u.SetLinkName(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *RepoMappingUpdateOne) SetKind(v repomapping.Kind) *RepoMappingUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *RepoMappingUpdateOne) SetNillableKind(v *repomapping.Kind) *RepoMappingUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *RepoMappingUpdateOne) SetState(v repomapping.State) *RepoMappingUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *RepoMappingUpdateOne) SetNillableState(v *repomapping.State) *RepoMappingUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetCreatedByEmail sets the "created_by_email" field.
func (_u *RepoMappingUpdateOne) SetCreatedByEmail(v string) *RepoMappingUpdateOne {
	_u.mutation.SetCreatedByEmail(v)
	return _u
}

// SetNillableCreatedByEmail sets the "created_by_email" field if the given value is not nil.
func (_u *RepoMappingUpdateOne) SetNillableCreatedByEmail(v *string) *RepoMappingUpdateOne {
	if v != nil {
		_u.SetCreatedByEmail(*v)
	}
	return _u
}

// ClearCreatedByEmail clears the value of the "created_by_email" field.
func (_u *RepoMappingUpdateOne) ClearCreatedByEmail() *RepoMappingUpdateOne {
	_u.mutation.ClearCreatedByEmail()
	return _u
}

// SetCreatedByName sets the "created_by_name" field.
func (_u *RepoMappingUpdateOne) SetCreatedByName(v string) *RepoMappingUpdateOne {
	_u.mutation.SetCreatedByName(v)
	return _u
}

// SetNillableCreatedByName sets the "created_by_name" field if the given value is not nil.
func (_u *RepoMappingUpdateOne) SetNillableCreatedByName(v *string) *RepoMappingUpdateOne {
	if v != nil {
		_u.SetCreatedByName(*v)
	}
	return _u
}

// ClearCreatedByName clears the value of the "created_by_name" field.
func (_u *RepoMappingUpdateOne) ClearCreatedByName() *RepoMappingUpdateOne {
	_u.mutation.ClearCreatedByName()
	return _u
}

// SetUpdatedByEmail sets the "updated_by_email" field.
func (_u *RepoMappingUpdateOne) SetUpdatedByEmail(v string) *RepoMappingUpdateOne {
	_u.mutation.SetUpdatedByEmail(v)
	return _u
}

// SetNillableUpdatedByEmail sets the "updated_by_email" field if the given value is not nil.
func (_u *RepoMappingUpdateOne) SetNillableUpdatedByEmail(v *string) *RepoMappingUpdateOne {
	if v != nil {
		_u.SetUpdatedByEmail(*v)
	}
	return _u
}

// ClearUpdatedByEmail clears the value of the "updated_by_email" field.
func (_u *RepoMappingUpdateOne) ClearUpdatedByEmail() *RepoMappingUpdateOne {
	_u.mutation.ClearUpdatedByEmail()
	return _u
}

// SetUpdatedByName sets the "updated_by_name" field.
func (_u *RepoMappingUpdateOne) SetUpdatedByName(v string) *RepoMappingUpdateOne {
	_u.mutation.SetUpdatedByName(v)
	return _u
}

// SetNillableUpdatedByName sets the "updated_by_name" field if the given value is not nil.
func (_u *RepoMappingUpdateOne) SetNillableUpdatedByName(v *string) *RepoMappingUpdateOne {
	if v != nil {
		_u.SetUpdatedByName(*v)
	}
	return _u
}

// ClearUpdatedByName clears the value of the "updated_by_name" field.
func (_u *RepoMappingUpdateOne) ClearUpdatedByName() *RepoMappingUpdateOne {
	_u.mutation.ClearUpdatedByName()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *RepoMappingUpdateOne) SetNotes(v string) *RepoMappingUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *RepoMappingUpdateOne) SetNillableNotes(v *string) *RepoMappingUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *RepoMappingUpdateOne) ClearNotes() *RepoMappingUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RepoMappingUpdateOne) SetUpdatedAt(v time.Time) *RepoMappingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the RepoMappingMutation object of the builder.
func (_u *RepoMappingUpdateOne) Mutation() *RepoMappingMutation {
	return _u.mutation
}

// Where appends a list predicates to the RepoMappingUpdate builder.
func (_u *RepoMappingUpdateOne) Where(ps ...predicate.RepoMapping) *RepoMappingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RepoMappingUpdateOne) Select(field string, fields ...string) *RepoMappingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RepoMapping entity.
func (_u *RepoMappingUpdateOne) Save(ctx context.Context) (*RepoMapping, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RepoMappingUpdateOne) SaveX(ctx context.Context) *RepoMapping {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RepoMappingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RepoMappingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RepoMappingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := repomapping.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RepoMappingUpdateOne) check() error {
	if v, ok := _u.mutation.SourceRel(); ok {
		if err := repomapping.SourceRelValidator(v); err != nil {
			return &ValidationError{Name: "source_rel", err: fmt.Errorf(`ent: validator failed for field "RepoMapping.source_rel": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RepoURL(); ok {
		if err := repomapping.RepoURLValidator(v); err != nil {
			return &ValidationError{Name: "repo_url", err: fmt.Errorf(`ent: validator failed for field "RepoMapping.repo_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LinkName(); ok {
		if err := repomapping.LinkNameValidator(v); err != nil {
			return &ValidationError{Name: "link_name", err: fmt.Errorf(`ent: validator failed for field "RepoMapping.link_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := repomapping.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "RepoMapping.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := repomapping.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "RepoMapping.state": %w`, err)}
		}
	}
	return nil
}

func (_u *RepoMappingUpdateOne) sqlSave(ctx context.Context) (_node *RepoMapping, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(repomapping.Table, repomapping.Columns, sqlgraph.NewFieldSpec(repomapping.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RepoMapping.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, repomapping.FieldID)
		for _, f := range fields {
			if !repomapping.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != repomapping.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceRel(); ok {
		_spec.SetField(repomapping.FieldSourceRel, field.TypeString, value)
	}
	if value, ok := _u.mutation.RepoURL(); ok {
		_spec.SetField(repomapping.FieldRepoURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetRel(); ok {
		_spec.SetField(repomapping.FieldTargetRel, field.TypeString, value)
	}
	if value, ok := _u.mutation.LinkName(); ok {
		_spec.SetField(repomapping.FieldLinkName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(repomapping.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(repomapping.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CreatedByEmail(); ok {
		_spec.SetField(repomapping.FieldCreatedByEmail, field.TypeString, value)
	}
	if _u.mutation.CreatedByEmailCleared() {
		_spec.ClearField(repomapping.FieldCreatedByEmail, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedByName(); ok {
		_spec.SetField(repomapping.FieldCreatedByName, field.TypeString, value)
	}
	if _u.mutation.CreatedByNameCleared() {
		_spec.ClearField(repomapping.FieldCreatedByName, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedByEmail(); ok {
		_spec.SetField(repomapping.FieldUpdatedByEmail, field.TypeString, value)
	}
	if _u.mutation.UpdatedByEmailCleared() {
		_spec.ClearField(repomapping.FieldUpdatedByEmail, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedByName(); ok {
		_spec.SetField(repomapping.FieldUpdatedByName, field.TypeString, value)
	}
	if _u.mutation.UpdatedByNameCleared() {
		_spec.ClearField(repomapping.FieldUpdatedByName, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(repomapping.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(repomapping.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(repomapping.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &RepoMapping{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repomapping.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
