// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/khanakia/repolink-go/internal/ent/repometa"
)

// RepoMetaCreate is the builder for creating a RepoMeta entity.
type RepoMetaCreate struct {
	config
	mutation *RepoMetaMutation
	hooks    []Hook
}

// SetPrivateRepoID sets the "private_repo_id" field.
func (_c *RepoMetaCreate) SetPrivateRepoID(v string) *RepoMetaCreate {
	_c.mutation.SetPrivateRepoID(v)
	return _c
}

// SetNillablePrivateRepoID sets the "private_repo_id" field if the given value is not nil.
func (_c *RepoMetaCreate) SetNillablePrivateRepoID(v *string) *RepoMetaCreate {
	if v != nil {
		_c.SetPrivateRepoID(*v)
	}
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *RepoMetaCreate) SetDisplayName(v string) *RepoMetaCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RepoMetaCreate) SetCreatedAt(v time.Time) *RepoMetaCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RepoMetaCreate) SetNillableCreatedAt(v *time.Time) *RepoMetaCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RepoMetaCreate) SetID(v string) *RepoMetaCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RepoMetaCreate) SetNillableID(v *string) *RepoMetaCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the RepoMetaMutation object of the builder.
func (_c *RepoMetaCreate) Mutation() *RepoMetaMutation {
	return _c.mutation
}

// Save creates the RepoMeta in the database.
func (_c *RepoMetaCreate) Save(ctx context.Context) (*RepoMeta, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RepoMetaCreate) SaveX(ctx context.Context) *RepoMeta {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RepoMetaCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RepoMetaCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RepoMetaCreate) defaults() {
	if _, ok := _c.mutation.PrivateRepoID(); !ok {
		v := repometa.DefaultPrivateRepoID()
		_c.mutation.SetPrivateRepoID(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := repometa.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := repometa.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RepoMetaCreate) check() error {
	if _, ok := _c.mutation.PrivateRepoID(); !ok {
		return &ValidationError{Name: "private_repo_id", err: errors.New(`ent: missing required field "RepoMeta.private_repo_id"`)}
	}
	if v, ok := _c.mutation.PrivateRepoID(); ok {
		if err := repometa.PrivateRepoIDValidator(v); err != nil {
			return &ValidationError{Name: "private_repo_id", err: fmt.Errorf(`ent: validator failed for field "RepoMeta.private_repo_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "RepoMeta.display_name"`)}
	}
	if v, ok := _c.mutation.DisplayName(); ok {
		if err := repometa.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "RepoMeta.display_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RepoMeta.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := repometa.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "RepoMeta.id": %w`, err)}
		}
	}
	return nil
}

func (_c *RepoMetaCreate) sqlSave(ctx context.Context) (*RepoMeta, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected RepoMeta.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RepoMetaCreate) createSpec() (*RepoMeta, *sqlgraph.CreateSpec) {
	var (
		_node = &RepoMeta{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(repometa.Table, sqlgraph.NewFieldSpec(repometa.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.PrivateRepoID(); ok {
		_spec.SetField(repometa.FieldPrivateRepoID, field.TypeString, value)
		_node.PrivateRepoID = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(repometa.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(repometa.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// RepoMetaCreateBulk is the builder for creating many RepoMeta entities in bulk.
type RepoMetaCreateBulk struct {
	config
	err      error
	builders []*RepoMetaCreate
}

// Save creates the RepoMeta entities in the database.
func (_c *RepoMetaCreateBulk) Save(ctx context.Context) ([]*RepoMeta, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RepoMeta, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RepoMetaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RepoMetaCreateBulk) SaveX(ctx context.Context) []*RepoMeta {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RepoMetaCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RepoMetaCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
