// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/khanakia/repolink-go/internal/ent/predicate"
	"github.com/khanakia/repolink-go/internal/ent/repometa"
)

// RepoMetaDelete is the builder for deleting a RepoMeta entity.
type RepoMetaDelete struct {
	config
	hooks    []Hook
	mutation *RepoMetaMutation
}

// Where appends a list predicates to the RepoMetaDelete builder.
func (_d *RepoMetaDelete) Where(ps ...predicate.RepoMeta) *RepoMetaDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RepoMetaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RepoMetaDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RepoMetaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(repometa.Table, sqlgraph.NewFieldSpec(repometa.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RepoMetaDeleteOne is the builder for deleting a single RepoMeta entity.
type RepoMetaDeleteOne struct {
	_d *RepoMetaDelete
}

// Where appends a list predicates to the RepoMetaDelete builder.
func (_d *RepoMetaDeleteOne) Where(ps ...predicate.RepoMeta) *RepoMetaDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RepoMetaDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{repometa.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RepoMetaDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
