// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/khanakia/repolink-go/internal/ent/predicate"
	"github.com/khanakia/repolink-go/internal/ent/runlog"
)

// RunLogUpdate is the builder for updating RunLog entities.
type RunLogUpdate struct {
	config
	hooks    []Hook
	mutation *RunLogMutation
}

// Where appends a list predicates to the RunLogUpdate builder.
func (_u *RunLogUpdate) Where(ps ...predicate.RunLog) *RunLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProfileID sets the "profile_id" field.
func (_u *RunLogUpdate) SetProfileID(v string) *RunLogUpdate {
	_u.mutation.SetProfileID(v)
	return _u
}

// SetNillableProfileID sets the "profile_id" field if the given value is not nil.
func (_u *RunLogUpdate) SetNillableProfileID(v *string) *RunLogUpdate {
	if v != nil {
		_u.SetProfileID(*v)
	}
	return _u
}

// SetMappingID sets the "mapping_id" field.
func (_u *RunLogUpdate) SetMappingID(v string) *RunLogUpdate {
	_u.mutation.SetMappingID(v)
	return _u
}

// SetNillableMappingID sets the "mapping_id" field if the given value is not nil.
func (_u *RunLogUpdate) SetNillableMappingID(v *string) *RunLogUpdate {
	if v != nil {
		_u.SetMappingID(*v)
	}
	return _u
}

// ClearMappingID clears the value of the "mapping_id" field.
func (_u *RunLogUpdate) ClearMappingID() *RunLogUpdate {
	_u.mutation.ClearMappingID()
	return _u
}

// SetOp sets the "op" field.
func (_u *RunLogUpdate) SetOp(v runlog.Op) *RunLogUpdate {
	_u.mutation.SetOpField(v)
	return _u
}

// SetNillableOp sets the "op" field if the given value is not nil.
func (_u *RunLogUpdate) SetNillableOp(v *runlog.Op) *RunLogUpdate {
	if v != nil {
		_u.SetOp(*v)
	}
	return _u
}

// SetResult sets the "result" field.
func (_u *RunLogUpdate) SetResult(v runlog.Result) *RunLogUpdate {
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *RunLogUpdate) SetNillableResult(v *runlog.Result) *RunLogUpdate {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// SetUserEmail sets the "user_email" field.
func (_u *RunLogUpdate) SetUserEmail(v string) *RunLogUpdate {
	_u.mutation.SetUserEmail(v)
	return _u
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_u *RunLogUpdate) SetNillableUserEmail(v *string) *RunLogUpdate {
	if v != nil {
		_u.SetUserEmail(*v)
	}
	return _u
}

// ClearUserEmail clears the value of the "user_email" field.
func (_u *RunLogUpdate) ClearUserEmail() *RunLogUpdate {
	_u.mutation.ClearUserEmail()
	return _u
}

// SetUserName sets the "user_name" field.
func (_u *RunLogUpdate) SetUserName(v string) *RunLogUpdate {
	_u.mutation.SetUserName(v)
	return _u
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (_u *RunLogUpdate) SetNillableUserName(v *string) *RunLogUpdate {
	if v != nil {
		_u.SetUserName(*v)
	}
	return _u
}

// ClearUserName clears the value of the "user_name" field.
func (_u *RunLogUpdate) ClearUserName() *RunLogUpdate {
	_u.mutation.ClearUserName()
	return _u
}

// SetMessage sets the "message" field.
func (_u *RunLogUpdate) SetMessage(v string) *RunLogUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *RunLogUpdate) SetNillableMessage(v *string) *RunLogUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *RunLogUpdate) ClearMessage() *RunLogUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// Mutation returns the RunLogMutation object of the builder.
func (_u *RunLogUpdate) Mutation() *RunLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RunLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RunLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RunLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RunLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RunLogUpdate) check() error {
	if v, ok := _u.mutation.GetOp(); ok {
		if err := runlog.OpValidator(v); err != nil {
			return &ValidationError{Name: "op", err: fmt.Errorf(`ent: validator failed for field "RunLog.op": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Result(); ok {
		if err := runlog.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`ent: validator failed for field "RunLog.result": %w`, err)}
		}
	}
	return nil
}

func (_u *RunLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(runlog.Table, runlog.Columns, sqlgraph.NewFieldSpec(runlog.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProfileID(); ok {
		_spec.SetField(runlog.FieldProfileID, field.TypeString, value)
	}
	if value, ok := _u.mutation.MappingID(); ok {
		_spec.SetField(runlog.FieldMappingID, field.TypeString, value)
	}
	if _u.mutation.MappingIDCleared() {
		_spec.ClearField(runlog.FieldMappingID, field.TypeString)
	}
	if value, ok := _u.mutation.GetOp(); ok {
		_spec.SetField(runlog.FieldOp, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(runlog.FieldResult, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UserEmail(); ok {
		_spec.SetField(runlog.FieldUserEmail, field.TypeString, value)
	}
	if _u.mutation.UserEmailCleared() {
		_spec.ClearField(runlog.FieldUserEmail, field.TypeString)
	}
	if value, ok := _u.mutation.UserName(); ok {
		_spec.SetField(runlog.FieldUserName, field.TypeString, value)
	}
	if _u.mutation.UserNameCleared() {
		_spec.ClearField(runlog.FieldUserName, field.TypeString)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(runlog.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(runlog.FieldMessage, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{runlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RunLogUpdateOne is the builder for updating a single RunLog entity.
type RunLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RunLogMutation
}

// SetProfileID sets the "profile_id" field.
func (_u *RunLogUpdateOne) SetProfileID(v string) *RunLogUpdateOne {
	_u.mutation.SetProfileID(v)
	return _u
}

// SetNillableProfileID sets the "profile_id" field if the given value is not nil.
func (_u *RunLogUpdateOne) SetNillableProfileID(v *string) *RunLogUpdateOne {
	if v != nil {
		_u.SetProfileID(*v)
	}
	return _u
}

// SetMappingID sets the "mapping_id" field.
func (_u *RunLogUpdateOne) SetMappingID(v string) *RunLogUpdateOne {
	_u.mutation.SetMappingID(v)
	return _u
}

// SetNillableMappingID sets the "mapping_id" field if the given value is not nil.
func (_u *RunLogUpdateOne) SetNillableMappingID(v *string) *RunLogUpdateOne {
	if v != nil {
		_u.SetMappingID(*v)
	}
	return _u
}

// ClearMappingID clears the value of the "mapping_id" field.
func (_u *RunLogUpdateOne) ClearMappingID() *RunLogUpdateOne {
	_u.mutation.ClearMappingID()
	return _u
}

// SetOp sets the "op" field.
func (_u *RunLogUpdateOne) SetOp(v runlog.Op) *RunLogUpdateOne {
	_u.mutation.SetOpField(v)
	return _u
}

// SetNillableOp sets the "op" field if the given value is not nil.
func (_u *RunLogUpdateOne) SetNillableOp(v *runlog.Op) *RunLogUpdateOne {
	if v != nil {
		_u.SetOp(*v)
	}
	return _u
}

// SetResult sets the "result" field.
func (_u *RunLogUpdateOne) SetResult(v runlog.Result) *RunLogUpdateOne {
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *RunLogUpdateOne) SetNillableResult(v *runlog.Result) *RunLogUpdateOne {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// SetUserEmail sets the "user_email" field.
func (_u *RunLogUpdateOne) SetUserEmail(v string) *RunLogUpdateOne {
	_u.mutation.SetUserEmail(v)
	return _u
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_u *RunLogUpdateOne) SetNillableUserEmail(v *string) *RunLogUpdateOne {
	if v != nil {
		_u.SetUserEmail(*v)
	}
	return _u
}

// ClearUserEmail clears the value of the "user_email" field.
func (_u *RunLogUpdateOne) ClearUserEmail() *RunLogUpdateOne {
	_u.mutation.ClearUserEmail()
	return _u
}

// SetUserName sets the "user_name" field.
func (_u *RunLogUpdateOne) SetUserName(v string) *RunLogUpdateOne {
	_u.mutation.SetUserName(v)
	return _u
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (_u *RunLogUpdateOne) SetNillableUserName(v *string) *RunLogUpdateOne {
	if v != nil {
		_u.SetUserName(*v)
	}
	return _u
}

// ClearUserName clears the value of the "user_name" field.
func (_u *RunLogUpdateOne) ClearUserName() *RunLogUpdateOne {
	_u.mutation.ClearUserName()
	return _u
}

// SetMessage sets the "message" field.
func (_u *RunLogUpdateOne) SetMessage(v string) *RunLogUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *RunLogUpdateOne) SetNillableMessage(v *string) *RunLogUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *RunLogUpdateOne) ClearMessage() *RunLogUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// Mutation returns the RunLogMutation object of the builder.
func (_u *RunLogUpdateOne) Mutation() *RunLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the RunLogUpdate builder.
func (_u *RunLogUpdateOne) Where(ps ...predicate.RunLog) *RunLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RunLogUpdateOne) Select(field string, fields ...string) *RunLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RunLog entity.
func (_u *RunLogUpdateOne) Save(ctx context.Context) (*RunLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RunLogUpdateOne) SaveX(ctx context.Context) *RunLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RunLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RunLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RunLogUpdateOne) check() error {
	if v, ok := _u.mutation.GetOp(); ok {
		if err := runlog.OpValidator(v); err != nil {
			return &ValidationError{Name: "op", err: fmt.Errorf(`ent: validator failed for field "RunLog.op": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Result(); ok {
		if err := runlog.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`ent: validator failed for field "RunLog.result": %w`, err)}
		}
	}
	return nil
}

func (_u *RunLogUpdateOne) sqlSave(ctx context.Context) (_node *RunLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(runlog.Table, runlog.Columns, sqlgraph.NewFieldSpec(runlog.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RunLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, runlog.FieldID)
		for _, f := range fields {
			if !runlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != runlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProfileID(); ok {
		_spec.SetField(runlog.FieldProfileID, field.TypeString, value)
	}
	if value, ok := _u.mutation.MappingID(); ok {
		_spec.SetField(runlog.FieldMappingID, field.TypeString, value)
	}
	if _u.mutation.MappingIDCleared() {
		_spec.ClearField(runlog.FieldMappingID, field.TypeString)
	}
	if value, ok := _u.mutation.GetOp(); ok {
		_spec.SetField(runlog.FieldOp, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(runlog.FieldResult, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UserEmail(); ok {
		_spec.SetField(runlog.FieldUserEmail, field.TypeString, value)
	}
	if _u.mutation.UserEmailCleared() {
		_spec.ClearField(runlog.FieldUserEmail, field.TypeString)
	}
	if value, ok := _u.mutation.UserName(); ok {
		_spec.SetField(runlog.FieldUserName, field.TypeString, value)
	}
	if _u.mutation.UserNameCleared() {
		_spec.ClearField(runlog.FieldUserName, field.TypeString)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(runlog.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(runlog.FieldMessage, field.TypeString)
	}
	_node = &RunLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{runlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
