// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/khanakia/repolink-go/internal/ent/runlog"
)

// RunLogCreate is the builder for creating a RunLog entity.
type RunLogCreate struct {
	config
	mutation *RunLogMutation
	hooks    []Hook
}

// SetProfileID sets the "profile_id" field.
func (_c *RunLogCreate) SetProfileID(v string) *RunLogCreate {
	_c.mutation.SetProfileID(v)
	return _c
}

// SetMappingID sets the "mapping_id" field.
func (_c *RunLogCreate) SetMappingID(v string) *RunLogCreate {
	_c.mutation.SetMappingID(v)
	return _c
}

// SetNillableMappingID sets the "mapping_id" field if the given value is not nil.
func (_c *RunLogCreate) SetNillableMappingID(v *string) *RunLogCreate {
	if v != nil {
		_c.SetMappingID(*v)
	}
	return _c
}

// SetOp sets the "op" field.
func (_c *RunLogCreate) SetOp(v runlog.Op) *RunLogCreate {
	_c.mutation.SetOpField(v)
	return _c
}

// SetResult sets the "result" field.
func (_c *RunLogCreate) SetResult(v runlog.Result) *RunLogCreate {
	_c.mutation.SetResult(v)
	return _c
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_c *RunLogCreate) SetNillableResult(v *runlog.Result) *RunLogCreate {
	if v != nil {
		_c.SetResult(*v)
	}
	return _c
}

// SetUserEmail sets the "user_email" field.
func (_c *RunLogCreate) SetUserEmail(v string) *RunLogCreate {
	_c.mutation.SetUserEmail(v)
	return _c
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_c *RunLogCreate) SetNillableUserEmail(v *string) *RunLogCreate {
	if v != nil {
		_c.SetUserEmail(*v)
	}
	return _c
}

// SetUserName sets the "user_name" field.
func (_c *RunLogCreate) SetUserName(v string) *RunLogCreate {
	_c.mutation.SetUserName(v)
	return _c
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (_c *RunLogCreate) SetNillableUserName(v *string) *RunLogCreate {
	if v != nil {
		_c.SetUserName(*v)
	}
	return _c
}

// SetMessage sets the "message" field.
func (_c *RunLogCreate) SetMessage(v string) *RunLogCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_c *RunLogCreate) SetNillableMessage(v *string) *RunLogCreate {
	if v != nil {
		_c.SetMessage(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RunLogCreate) SetCreatedAt(v time.Time) *RunLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RunLogCreate) SetNillableCreatedAt(v *time.Time) *RunLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RunLogCreate) SetID(v string) *RunLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RunLogCreate) SetNillableID(v *string) *RunLogCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the RunLogMutation object of the builder.
func (_c *RunLogCreate) Mutation() *RunLogMutation {
	return _c.mutation
}

// Save creates the RunLog in the database.
func (_c *RunLogCreate) Save(ctx context.Context) (*RunLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RunLogCreate) SaveX(ctx context.Context) *RunLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RunLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RunLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RunLogCreate) defaults() {
	if _, ok := _c.mutation.Result(); !ok {
		v := runlog.DefaultResult
		_c.mutation.SetResult(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := runlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := runlog.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RunLogCreate) check() error {
	if _, ok := _c.mutation.ProfileID(); !ok {
		return &ValidationError{Name: "profile_id", err: errors.New(`ent: missing required field "RunLog.profile_id"`)}
	}
	if _, ok := _c.mutation.GetOp(); !ok {
		return &ValidationError{Name: "op", err: errors.New(`ent: missing required field "RunLog.op"`)}
	}
	if v, ok := _c.mutation.GetOp(); ok {
		if err := runlog.OpValidator(v); err != nil {
			return &ValidationError{Name: "op", err: fmt.Errorf(`ent: validator failed for field "RunLog.op": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Result(); !ok {
		return &ValidationError{Name: "result", err: errors.New(`ent: missing required field "RunLog.result"`)}
	}
	if v, ok := _c.mutation.Result(); ok {
		if err := runlog.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`ent: validator failed for field "RunLog.result": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RunLog.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := runlog.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "RunLog.id": %w`, err)}
		}
	}
	return nil
}

func (_c *RunLogCreate) sqlSave(ctx context.Context) (*RunLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected RunLog.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RunLogCreate) createSpec() (*RunLog, *sqlgraph.CreateSpec) {
	var (
		_node = &RunLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(runlog.Table, sqlgraph.NewFieldSpec(runlog.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ProfileID(); ok {
		_spec.SetField(runlog.FieldProfileID, field.TypeString, value)
		_node.ProfileID = value
	}
	if value, ok := _c.mutation.MappingID(); ok {
		_spec.SetField(runlog.FieldMappingID, field.TypeString, value)
		_node.MappingID = &value
	}
	if value, ok := _c.mutation.GetOp(); ok {
		_spec.SetField(runlog.FieldOp, field.TypeEnum, value)
		_node.Op = value
	}
	if value, ok := _c.mutation.Result(); ok {
		_spec.SetField(runlog.FieldResult, field.TypeEnum, value)
		_node.Result = value
	}
	if value, ok := _c.mutation.UserEmail(); ok {
		_spec.SetField(runlog.FieldUserEmail, field.TypeString, value)
		_node.UserEmail = value
	}
	if value, ok := _c.mutation.UserName(); ok {
		_spec.SetField(runlog.FieldUserName, field.TypeString, value)
		_node.UserName = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(runlog.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(runlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// RunLogCreateBulk is the builder for creating many RunLog entities in bulk.
type RunLogCreateBulk struct {
	config
	err      error
	builders []*RunLogCreate
}

// Save creates the RunLog entities in the database.
func (_c *RunLogCreateBulk) Save(ctx context.Context) ([]*RunLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RunLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RunLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RunLogCreateBulk) SaveX(ctx context.Context) []*RunLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RunLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RunLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
