// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/khanakia/repolink-go/internal/ent/profile"
	"github.com/khanakia/repolink-go/internal/ent/repomapping"
	"github.com/khanakia/repolink-go/internal/ent/repometa"
	"github.com/khanakia/repolink-go/internal/ent/runlog"
	"github.com/khanakia/repolink-go/internal/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	profileFields := schema.Profile{}.Fields()
	_ = profileFields
	// profileDescName is the schema descriptor for name field.
	profileDescName := profileFields[1].Descriptor()
	// profile.NameValidator is a validator for the "name" field. It is called by the builders before save.
	profile.NameValidator = profileDescName.Validators[0].(func(string) error)
	// profileDescCreatedAt is the schema descriptor for created_at field.
	profileDescCreatedAt := profileFields[3].Descriptor()
	// profile.DefaultCreatedAt holds the default value on creation for the created_at field.
	profile.DefaultCreatedAt = profileDescCreatedAt.Default.(func() time.Time)
	// profileDescUpdatedAt is the schema descriptor for updated_at field.
	profileDescUpdatedAt := profileFields[4].Descriptor()
	// profile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	profile.DefaultUpdatedAt = profileDescUpdatedAt.Default.(func() time.Time)
	// profile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	profile.UpdateDefaultUpdatedAt = profileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// profileDescID is the schema descriptor for id field.
	profileDescID := profileFields[0].Descriptor()
	// profile.DefaultID holds the default value on creation for the id field.
	profile.DefaultID = profileDescID.Default.(func() string)
	// profile.IDValidator is a validator for the "id" field. It is called by the builders before save.
	profile.IDValidator = profileDescID.Validators[0].(func(string) error)
	repomappingFields := schema.RepoMapping{}.Fields()
	_ = repomappingFields
	// repomappingDescSourceRel is the schema descriptor for source_rel field.
	repomappingDescSourceRel := repomappingFields[1].Descriptor()
	// repomapping.SourceRelValidator is a validator for the "source_rel" field. It is called by the builders before save.
	repomapping.SourceRelValidator = repomappingDescSourceRel.Validators[0].(func(string) error)
	// repomappingDescRepoURL is the schema descriptor for repo_url field.
	repomappingDescRepoURL := repomappingFields[2].Descriptor()
	// repomapping.RepoURLValidator is a validator for the "repo_url" field. It is called by the builders before save.
	repomapping.RepoURLValidator = repomappingDescRepoURL.Validators[0].(func(string) error)
	// repomappingDescLinkName is the schema descriptor for link_name field.
	repomappingDescLinkName := repomappingFields[4].Descriptor()
	// repomapping.LinkNameValidator is a validator for the "link_name" field. It is called by the builders before save.
	repomapping.LinkNameValidator = repomappingDescLinkName.Validators[0].(func(string) error)
	// repomappingDescCreatedAt is the schema descriptor for created_at field.
	repomappingDescCreatedAt := repomappingFields[12].Descriptor()
	// repomapping.DefaultCreatedAt holds the default value on creation for the created_at field.
	repomapping.DefaultCreatedAt = repomappingDescCreatedAt.Default.(func() time.Time)
	// repomappingDescUpdatedAt is the schema descriptor for updated_at field.
	repomappingDescUpdatedAt := repomappingFields[13].Descriptor()
	// repomapping.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	repomapping.DefaultUpdatedAt = repomappingDescUpdatedAt.Default.(func() time.Time)
	// repomapping.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	repomapping.UpdateDefaultUpdatedAt = repomappingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// repomappingDescID is the schema descriptor for id field.
	repomappingDescID := repomappingFields[0].Descriptor()
	// repomapping.DefaultID holds the default value on creation for the id field.
	repomapping.DefaultID = repomappingDescID.Default.(func() string)
	// repomapping.IDValidator is a validator for the "id" field. It is called by the builders before save.
	repomapping.IDValidator = repomappingDescID.Validators[0].(func(string) error)
	repometaFields := schema.RepoMeta{}.Fields()
	_ = repometaFields
	// repometaDescPrivateRepoID is the schema descriptor for private_repo_id field.
	repometaDescPrivateRepoID := repometaFields[1].Descriptor()
	// repometa.DefaultPrivateRepoID holds the default value on creation for the private_repo_id field.
	repometa.DefaultPrivateRepoID = repometaDescPrivateRepoID.Default.(func() string)
	// repometa.PrivateRepoIDValidator is a validator for the "private_repo_id" field. It is called by the builders before save.
	repometa.PrivateRepoIDValidator = repometaDescPrivateRepoID.Validators[0].(func(string) error)
	// repometaDescDisplayName is the schema descriptor for display_name field.
	repometaDescDisplayName := repometaFields[2].Descriptor()
	// repometa.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	repometa.DisplayNameValidator = repometaDescDisplayName.Validators[0].(func(string) error)
	// repometaDescCreatedAt is the schema descriptor for created_at field.
	repometaDescCreatedAt := repometaFields[3].Descriptor()
	// repometa.DefaultCreatedAt holds the default value on creation for the created_at field.
	repometa.DefaultCreatedAt = repometaDescCreatedAt.Default.(func() time.Time)
	// repometaDescID is the schema descriptor for id field.
	repometaDescID := repometaFields[0].Descriptor()
	// repometa.DefaultID holds the default value on creation for the id field.
	repometa.DefaultID = repometaDescID.Default.(func() string)
	// repometa.IDValidator is a validator for the "id" field. It is called by the builders before save.
	repometa.IDValidator = repometaDescID.Validators[0].(func(string) error)
	runlogFields := schema.RunLog{}.Fields()
	_ = runlogFields
	// runlogDescCreatedAt is the schema descriptor for created_at field.
	runlogDescCreatedAt := runlogFields[8].Descriptor()
	// runlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	runlog.DefaultCreatedAt = runlogDescCreatedAt.Default.(func() time.Time)
	// runlogDescID is the schema descriptor for id field.
	runlogDescID := runlogFields[0].Descriptor()
	// runlog.DefaultID holds the default value on creation for the id field.
	runlog.DefaultID = runlogDescID.Default.(func() string)
	// runlog.IDValidator is a validator for the "id" field. It is called by the builders before save.
	runlog.IDValidator = runlogDescID.Validators[0].(func(string) error)
}
