// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Profile is the predicate function for profile builders.
type Profile func(*sql.Selector)

// RepoMapping is the predicate function for repomapping builders.
type RepoMapping func(*sql.Selector)

// RepoMeta is the predicate function for repometa builders.
type RepoMeta func(*sql.Selector)

// RunLog is the predicate function for runlog builders.
type RunLog func(*sql.Selector)
