// Code generated by ent, DO NOT EDIT.

package runlog

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the runlog type in the database.
	Label = "run_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProfileID holds the string denoting the profile_id field in the database.
	FieldProfileID = "profile_id"
	// FieldMappingID holds the string denoting the mapping_id field in the database.
	FieldMappingID = "mapping_id"
	// FieldOp holds the string denoting the op field in the database.
	FieldOp = "op"
	// FieldResult holds the string denoting the result field in the database.
	FieldResult = "result"
	// FieldUserEmail holds the string denoting the user_email field in the database.
	FieldUserEmail = "user_email"
	// FieldUserName holds the string denoting the user_name field in the database.
	FieldUserName = "user_name"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the runlog in the database.
	Table = "run_logs"
)

// Columns holds all SQL columns for runlog fields.
var Columns = []string{
	FieldID,
	FieldProfileID,
	FieldMappingID,
	FieldOp,
	FieldResult,
	FieldUserEmail,
	FieldUserName,
	FieldMessage,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// Op defines the type for the "op" enum field.
type Op string

// Op values.
const (
	OpSetup   Op = "setup"
	OpSync    Op = "sync"
	OpUnsync  Op = "unsync"
	OpLink    Op = "link"
	OpUnlink  Op = "unlink"
	OpPause   Op = "pause"
	OpResume  Op = "resume"
	OpCleanup Op = "cleanup"
	OpPurge   Op = "purge"
	OpMapMv   Op = "map_mv"
	OpVerify  Op = "verify"
	OpMeta    Op = "meta"
	OpConfig  Op = "config"
)

func (_op Op) String() string {
	return string(_op)
}

// OpValidator is a validator for the "op" field enum values. It is called by the builders before save.
func OpValidator(_op Op) error {
	switch _op {
	case OpSetup, OpSync, OpUnsync, OpLink, OpUnlink, OpPause, OpResume, OpCleanup, OpPurge, OpMapMv, OpVerify, OpMeta, OpConfig:
		return nil
	default:
		return fmt.Errorf("runlog: invalid enum value for op field: %q", _op)
	}
}

// Result defines the type for the "result" enum field.
type Result string

// ResultOk is the default value of the Result enum.
const DefaultResult = ResultOk

// Result values.
const (
	ResultOk    Result = "ok"
	ResultError Result = "error"
)

func (r Result) String() string {
	return string(r)
}

// ResultValidator is a validator for the "result" field enum values. It is called by the builders before save.
func ResultValidator(r Result) error {
	switch r {
	case ResultOk, ResultError:
		return nil
	default:
		return fmt.Errorf("runlog: invalid enum value for result field: %q", r)
	}
}

// OrderOption defines the ordering options for the RunLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProfileID orders the results by the profile_id field.
func ByProfileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProfileID, opts...).ToFunc()
}

// ByMappingID orders the results by the mapping_id field.
func ByMappingID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMappingID, opts...).ToFunc()
}

// ByOp orders the results by the op field.
func ByOp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOp, opts...).ToFunc()
}

// ByResult orders the results by the result field.
func ByResult(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResult, opts...).ToFunc()
}

// ByUserEmail orders the results by the user_email field.
func ByUserEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserEmail, opts...).ToFunc()
}

// ByUserName orders the results by the user_name field.
func ByUserName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserName, opts...).ToFunc()
}

// ByMessage orders the results by the message field.
func ByMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessage, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
