// Code generated by ent, DO NOT EDIT.

package runlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/khanakia/repolink-go/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.RunLog {
	return predicate.RunLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.RunLog {
	return predicate.RunLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.RunLog {
	return predicate.RunLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.RunLog {
	return predicate.RunLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.RunLog {
	return predicate.RunLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.RunLog {
	return predicate.RunLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.RunLog {
	return predicate.RunLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.RunLog {
	return predicate.RunLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.RunLog {
	return predicate.RunLog(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.RunLog {
	return predicate.RunLog(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.RunLog {
	return predicate.RunLog(sql.FieldContainsFold(FieldID, id))
}

// ProfileID applies equality check predicate on the "profile_id" field. It's identical to ProfileIDEQ.
func ProfileID(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldEQ(FieldProfileID, v))
}

// MappingID applies equality check predicate on the "mapping_id" field. It's identical to MappingIDEQ.
func MappingID(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldEQ(FieldMappingID, v))
}

// UserEmail applies equality check predicate on the "user_email" field. It's identical to UserEmailEQ.
func UserEmail(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldEQ(FieldUserEmail, v))
}

// UserName applies equality check predicate on the "user_name" field. It's identical to UserNameEQ.
func UserName(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldEQ(FieldUserName, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldEQ(FieldMessage, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RunLog {
	return predicate.RunLog(sql.FieldEQ(FieldCreatedAt, v))
}

// ProfileIDEQ applies the EQ predicate on the "profile_id" field.
func ProfileIDEQ(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldEQ(FieldProfileID, v))
}

// ProfileIDNEQ applies the NEQ predicate on the "profile_id" field.
func ProfileIDNEQ(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldNEQ(FieldProfileID, v))
}

// ProfileIDIn applies the In predicate on the "profile_id" field.
func ProfileIDIn(vs ...string) predicate.RunLog {
	return predicate.RunLog(sql.FieldIn(FieldProfileID, vs...))
}

// ProfileIDNotIn applies the NotIn predicate on the "profile_id" field.
func ProfileIDNotIn(vs ...string) predicate.RunLog {
	return predicate.RunLog(sql.FieldNotIn(FieldProfileID, vs...))
}

// ProfileIDGT applies the GT predicate on the "profile_id" field.
func ProfileIDGT(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldGT(FieldProfileID, v))
}

// ProfileIDGTE applies the GTE predicate on the "profile_id" field.
func ProfileIDGTE(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldGTE(FieldProfileID, v))
}

// ProfileIDLT applies the LT predicate on the "profile_id" field.
func ProfileIDLT(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldLT(FieldProfileID, v))
}

// ProfileIDLTE applies the LTE predicate on the "profile_id" field.
func ProfileIDLTE(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldLTE(FieldProfileID, v))
}

// ProfileIDContains applies the Contains predicate on the "profile_id" field.
func ProfileIDContains(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldContains(FieldProfileID, v))
}

// ProfileIDHasPrefix applies the HasPrefix predicate on the "profile_id" field.
func ProfileIDHasPrefix(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldHasPrefix(FieldProfileID, v))
}

// ProfileIDHasSuffix applies the HasSuffix predicate on the "profile_id" field.
func ProfileIDHasSuffix(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldHasSuffix(FieldProfileID, v))
}

// ProfileIDEqualFold applies the EqualFold predicate on the "profile_id" field.
func ProfileIDEqualFold(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldEqualFold(FieldProfileID, v))
}

// ProfileIDContainsFold applies the ContainsFold predicate on the "profile_id" field.
func ProfileIDContainsFold(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldContainsFold(FieldProfileID, v))
}

// MappingIDEQ applies the EQ predicate on the "mapping_id" field.
func MappingIDEQ(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldEQ(FieldMappingID, v))
}

// MappingIDNEQ applies the NEQ predicate on the "mapping_id" field.
func MappingIDNEQ(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldNEQ(FieldMappingID, v))
}

// MappingIDIn applies the In predicate on the "mapping_id" field.
func MappingIDIn(vs ...string) predicate.RunLog {
	return predicate.RunLog(sql.FieldIn(FieldMappingID, vs...))
}

// MappingIDNotIn applies the NotIn predicate on the "mapping_id" field.
func MappingIDNotIn(vs ...string) predicate.RunLog {
	return predicate.RunLog(sql.FieldNotIn(FieldMappingID, vs...))
}

// MappingIDGT applies the GT predicate on the "mapping_id" field.
func MappingIDGT(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldGT(FieldMappingID, v))
}

// MappingIDGTE applies the GTE predicate on the "mapping_id" field.
func MappingIDGTE(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldGTE(FieldMappingID, v))
}

// MappingIDLT applies the LT predicate on the "mapping_id" field.
func MappingIDLT(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldLT(FieldMappingID, v))
}

// MappingIDLTE applies the LTE predicate on the "mapping_id" field.
func MappingIDLTE(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldLTE(FieldMappingID, v))
}

// MappingIDContains applies the Contains predicate on the "mapping_id" field.
func MappingIDContains(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldContains(FieldMappingID, v))
}

// MappingIDHasPrefix applies the HasPrefix predicate on the "mapping_id" field.
func MappingIDHasPrefix(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldHasPrefix(FieldMappingID, v))
}

// MappingIDHasSuffix applies the HasSuffix predicate on the "mapping_id" field.
func MappingIDHasSuffix(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldHasSuffix(FieldMappingID, v))
}

// MappingIDIsNil applies the IsNil predicate on the "mapping_id" field.
func MappingIDIsNil() predicate.RunLog {
	return predicate.RunLog(sql.FieldIsNull(FieldMappingID))
}

// MappingIDNotNil applies the NotNil predicate on the "mapping_id" field.
func MappingIDNotNil() predicate.RunLog {
	return predicate.RunLog(sql.FieldNotNull(FieldMappingID))
}

// MappingIDEqualFold applies the EqualFold predicate on the "mapping_id" field.
func MappingIDEqualFold(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldEqualFold(FieldMappingID, v))
}

// MappingIDContainsFold applies the ContainsFold predicate on the "mapping_id" field.
func MappingIDContainsFold(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldContainsFold(FieldMappingID, v))
}

// OpEQ applies the EQ predicate on the "op" field.
func OpEQ(v Op) predicate.RunLog {
	return predicate.RunLog(sql.FieldEQ(FieldOp, v))
}

// OpNEQ applies the NEQ predicate on the "op" field.
func OpNEQ(v Op) predicate.RunLog {
	return predicate.RunLog(sql.FieldNEQ(FieldOp, v))
}

// OpIn applies the In predicate on the "op" field.
func OpIn(vs ...Op) predicate.RunLog {
	return predicate.RunLog(sql.FieldIn(FieldOp, vs...))
}

// OpNotIn applies the NotIn predicate on the "op" field.
func OpNotIn(vs ...Op) predicate.RunLog {
	return predicate.RunLog(sql.FieldNotIn(FieldOp, vs...))
}

// ResultEQ applies the EQ predicate on the "result" field.
func ResultEQ(v Result) predicate.RunLog {
	return predicate.RunLog(sql.FieldEQ(FieldResult, v))
}

// ResultNEQ applies the NEQ predicate on the "result" field.
func ResultNEQ(v Result) predicate.RunLog {
	return predicate.RunLog(sql.FieldNEQ(FieldResult, v))
}

// ResultIn applies the In predicate on the "result" field.
func ResultIn(vs ...Result) predicate.RunLog {
	return predicate.RunLog(sql.FieldIn(FieldResult, vs...))
}

// ResultNotIn applies the NotIn predicate on the "result" field.
func ResultNotIn(vs ...Result) predicate.RunLog {
	return predicate.RunLog(sql.FieldNotIn(FieldResult, vs...))
}

// UserEmailEQ applies the EQ predicate on the "user_email" field.
func UserEmailEQ(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldEQ(FieldUserEmail, v))
}

// UserEmailNEQ applies the NEQ predicate on the "user_email" field.
func UserEmailNEQ(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldNEQ(FieldUserEmail, v))
}

// UserEmailIn applies the In predicate on the "user_email" field.
func UserEmailIn(vs ...string) predicate.RunLog {
	return predicate.RunLog(sql.FieldIn(FieldUserEmail, vs...))
}

// UserEmailNotIn applies the NotIn predicate on the "user_email" field.
func UserEmailNotIn(vs ...string) predicate.RunLog {
	return predicate.RunLog(sql.FieldNotIn(FieldUserEmail, vs...))
}

// UserEmailGT applies the GT predicate on the "user_email" field.
func UserEmailGT(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldGT(FieldUserEmail, v))
}

// UserEmailGTE applies the GTE predicate on the "user_email" field.
func UserEmailGTE(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldGTE(FieldUserEmail, v))
}

// UserEmailLT applies the LT predicate on the "user_email" field.
func UserEmailLT(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldLT(FieldUserEmail, v))
}

// UserEmailLTE applies the LTE predicate on the "user_email" field.
func UserEmailLTE(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldLTE(FieldUserEmail, v))
}

// UserEmailContains applies the Contains predicate on the "user_email" field.
func UserEmailContains(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldContains(FieldUserEmail, v))
}

// UserEmailHasPrefix applies the HasPrefix predicate on the "user_email" field.
func UserEmailHasPrefix(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldHasPrefix(FieldUserEmail, v))
}

// UserEmailHasSuffix applies the HasSuffix predicate on the "user_email" field.
func UserEmailHasSuffix(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldHasSuffix(FieldUserEmail, v))
}

// UserEmailIsNil applies the IsNil predicate on the "user_email" field.
func UserEmailIsNil() predicate.RunLog {
	return predicate.RunLog(sql.FieldIsNull(FieldUserEmail))
}

// UserEmailNotNil applies the NotNil predicate on the "user_email" field.
func UserEmailNotNil() predicate.RunLog {
	return predicate.RunLog(sql.FieldNotNull(FieldUserEmail))
}

// UserEmailEqualFold applies the EqualFold predicate on the "user_email" field.
func UserEmailEqualFold(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldEqualFold(FieldUserEmail, v))
}

// UserEmailContainsFold applies the ContainsFold predicate on the "user_email" field.
func UserEmailContainsFold(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldContainsFold(FieldUserEmail, v))
}

// UserNameEQ applies the EQ predicate on the "user_name" field.
func UserNameEQ(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldEQ(FieldUserName, v))
}

// UserNameNEQ applies the NEQ predicate on the "user_name" field.
func UserNameNEQ(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldNEQ(FieldUserName, v))
}

// UserNameIn applies the In predicate on the "user_name" field.
func UserNameIn(vs ...string) predicate.RunLog {
	return predicate.RunLog(sql.FieldIn(FieldUserName, vs...))
}

// UserNameNotIn applies the NotIn predicate on the "user_name" field.
func UserNameNotIn(vs ...string) predicate.RunLog {
	return predicate.RunLog(sql.FieldNotIn(FieldUserName, vs...))
}

// UserNameGT applies the GT predicate on the "user_name" field.
func UserNameGT(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldGT(FieldUserName, v))
}

// UserNameGTE applies the GTE predicate on the "user_name" field.
func UserNameGTE(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldGTE(FieldUserName, v))
}

// UserNameLT applies the LT predicate on the "user_name" field.
func UserNameLT(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldLT(FieldUserName, v))
}

// UserNameLTE applies the LTE predicate on the "user_name" field.
func UserNameLTE(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldLTE(FieldUserName, v))
}

// UserNameContains applies the Contains predicate on the "user_name" field.
func UserNameContains(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldContains(FieldUserName, v))
}

// UserNameHasPrefix applies the HasPrefix predicate on the "user_name" field.
func UserNameHasPrefix(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldHasPrefix(FieldUserName, v))
}

// UserNameHasSuffix applies the HasSuffix predicate on the "user_name" field.
func UserNameHasSuffix(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldHasSuffix(FieldUserName, v))
}

// UserNameIsNil applies the IsNil predicate on the "user_name" field.
func UserNameIsNil() predicate.RunLog {
	return predicate.RunLog(sql.FieldIsNull(FieldUserName))
}

// UserNameNotNil applies the NotNil predicate on the "user_name" field.
func UserNameNotNil() predicate.RunLog {
	return predicate.RunLog(sql.FieldNotNull(FieldUserName))
}

// UserNameEqualFold applies the EqualFold predicate on the "user_name" field.
func UserNameEqualFold(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldEqualFold(FieldUserName, v))
}

// UserNameContainsFold applies the ContainsFold predicate on the "user_name" field.
func UserNameContainsFold(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldContainsFold(FieldUserName, v))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.RunLog {
	return predicate.RunLog(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.RunLog {
	return predicate.RunLog(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageIsNil applies the IsNil predicate on the "message" field.
func MessageIsNil() predicate.RunLog {
	return predicate.RunLog(sql.FieldIsNull(FieldMessage))
}

// MessageNotNil applies the NotNil predicate on the "message" field.
func MessageNotNil() predicate.RunLog {
	return predicate.RunLog(sql.FieldNotNull(FieldMessage))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.RunLog {
	return predicate.RunLog(sql.FieldContainsFold(FieldMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RunLog {
	return predicate.RunLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RunLog {
	return predicate.RunLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RunLog {
	return predicate.RunLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RunLog {
	return predicate.RunLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RunLog {
	return predicate.RunLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RunLog {
	return predicate.RunLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RunLog {
	return predicate.RunLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RunLog {
	return predicate.RunLog(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RunLog) predicate.RunLog {
	return predicate.RunLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RunLog) predicate.RunLog {
	return predicate.RunLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RunLog) predicate.RunLog {
	return predicate.RunLog(sql.NotPredicates(p))
}
