// Code generated by ent, DO NOT EDIT.

package repomapping

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the repomapping type in the database.
	Label = "repo_mapping"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSourceRel holds the string denoting the source_rel field in the database.
	FieldSourceRel = "source_rel"
	// FieldRepoURL holds the string denoting the repo_url field in the database.
	FieldRepoURL = "repo_url"
	// FieldTargetRel holds the string denoting the target_rel field in the database.
	FieldTargetRel = "target_rel"
	// FieldLinkName holds the string denoting the link_name field in the database.
	FieldLinkName = "link_name"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldCreatedByEmail holds the string denoting the created_by_email field in the database.
	FieldCreatedByEmail = "created_by_email"
	// FieldCreatedByName holds the string denoting the created_by_name field in the database.
	FieldCreatedByName = "created_by_name"
	// FieldUpdatedByEmail holds the string denoting the updated_by_email field in the database.
	FieldUpdatedByEmail = "updated_by_email"
	// FieldUpdatedByName holds the string denoting the updated_by_name field in the database.
	FieldUpdatedByName = "updated_by_name"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the repomapping in the database.
	Table = "repo_mappings"
)

// Columns holds all SQL columns for repomapping fields.
var Columns = []string{
	FieldID,
	FieldSourceRel,
	FieldRepoURL,
	FieldTargetRel,
	FieldLinkName,
	FieldKind,
	FieldState,
	FieldCreatedByEmail,
	FieldCreatedByName,
	FieldUpdatedByEmail,
	FieldUpdatedByName,
	FieldNotes,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SourceRelValidator is a validator for the "source_rel" field. It is called by the builders before save.
	SourceRelValidator func(string) error
	// RepoURLValidator is a validator for the "repo_url" field. It is called by the builders before save.
	RepoURLValidator func(string) error
	// LinkNameValidator is a validator for the "link_name" field. It is called by the builders before save.
	LinkNameValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// Kind defines the type for the "kind" enum field.
type Kind string

// KindDir is the default value of the Kind enum.
const DefaultKind = KindDir

// Kind values.
const (
	KindDir  Kind = "dir"
	KindFile Kind = "file"
)

func (k Kind) String() string {
	return string(k)
}

// KindValidator is a validator for the "kind" field enum values. It is called by the builders before save.
func KindValidator(k Kind) error {
	switch k {
	case KindDir, KindFile:
		return nil
	default:
		return fmt.Errorf("repomapping: invalid enum value for kind field: %q", k)
	}
}

// State defines the type for the "state" enum field.
type State string

// StateActive is the default value of the State enum.
const DefaultState = StateActive

// State values.
const (
	StateActive  State = "active"
	StatePaused  State = "paused"
	StateTrashed State = "trashed"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StateActive, StatePaused, StateTrashed:
		return nil
	default:
		return fmt.Errorf("repomapping: invalid enum value for state field: %q", s)
	}
}

// OrderOption defines the ordering options for the RepoMapping queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySourceRel orders the results by the source_rel field.
func BySourceRel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceRel, opts...).ToFunc()
}

// ByRepoURL orders the results by the repo_url field.
func ByRepoURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepoURL, opts...).ToFunc()
}

// ByTargetRel orders the results by the target_rel field.
func ByTargetRel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetRel, opts...).ToFunc()
}

// ByLinkName orders the results by the link_name field.
func ByLinkName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLinkName, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByCreatedByEmail orders the results by the created_by_email field.
func ByCreatedByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedByEmail, opts...).ToFunc()
}

// ByCreatedByName orders the results by the created_by_name field.
func ByCreatedByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedByName, opts...).ToFunc()
}

// ByUpdatedByEmail orders the results by the updated_by_email field.
func ByUpdatedByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedByEmail, opts...).ToFunc()
}

// ByUpdatedByName orders the results by the updated_by_name field.
func ByUpdatedByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedByName, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
