// Code generated by ent, DO NOT EDIT.

package repomapping

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/khanakia/repolink-go/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldContainsFold(FieldID, id))
}

// SourceRel applies equality check predicate on the "source_rel" field. It's identical to SourceRelEQ.
func SourceRel(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEQ(FieldSourceRel, v))
}

// RepoURL applies equality check predicate on the "repo_url" field. It's identical to RepoURLEQ.
func RepoURL(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEQ(FieldRepoURL, v))
}

// TargetRel applies equality check predicate on the "target_rel" field. It's identical to TargetRelEQ.
func TargetRel(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEQ(FieldTargetRel, v))
}

// LinkName applies equality check predicate on the "link_name" field. It's identical to LinkNameEQ.
func LinkName(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEQ(FieldLinkName, v))
}

// CreatedByEmail applies equality check predicate on the "created_by_email" field. It's identical to CreatedByEmailEQ.
func CreatedByEmail(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEQ(FieldCreatedByEmail, v))
}

// CreatedByName applies equality check predicate on the "created_by_name" field. It's identical to CreatedByNameEQ.
func CreatedByName(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEQ(FieldCreatedByName, v))
}

// UpdatedByEmail applies equality check predicate on the "updated_by_email" field. It's identical to UpdatedByEmailEQ.
func UpdatedByEmail(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEQ(FieldUpdatedByEmail, v))
}

// UpdatedByName applies equality check predicate on the "updated_by_name" field. It's identical to UpdatedByNameEQ.
func UpdatedByName(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEQ(FieldUpdatedByName, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEQ(FieldNotes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEQ(FieldUpdatedAt, v))
}

// SourceRelEQ applies the EQ predicate on the "source_rel" field.
func SourceRelEQ(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEQ(FieldSourceRel, v))
}

// SourceRelNEQ applies the NEQ predicate on the "source_rel" field.
func SourceRelNEQ(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNEQ(FieldSourceRel, v))
}

// SourceRelIn applies the In predicate on the "source_rel" field.
func SourceRelIn(vs ...string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldIn(FieldSourceRel, vs...))
}

// SourceRelNotIn applies the NotIn predicate on the "source_rel" field.
func SourceRelNotIn(vs ...string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNotIn(FieldSourceRel, vs...))
}

// SourceRelGT applies the GT predicate on the "source_rel" field.
func SourceRelGT(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldGT(FieldSourceRel, v))
}

// SourceRelGTE applies the GTE predicate on the "source_rel" field.
func SourceRelGTE(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldGTE(FieldSourceRel, v))
}

// SourceRelLT applies the LT predicate on the "source_rel" field.
func SourceRelLT(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldLT(FieldSourceRel, v))
}

// SourceRelLTE applies the LTE predicate on the "source_rel" field.
func SourceRelLTE(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldLTE(FieldSourceRel, v))
}

// SourceRelContains applies the Contains predicate on the "source_rel" field.
func SourceRelContains(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldContains(FieldSourceRel, v))
}

// SourceRelHasPrefix applies the HasPrefix predicate on the "source_rel" field.
func SourceRelHasPrefix(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldHasPrefix(FieldSourceRel, v))
}

// SourceRelHasSuffix applies the HasSuffix predicate on the "source_rel" field.
func SourceRelHasSuffix(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldHasSuffix(FieldSourceRel, v))
}

// SourceRelEqualFold applies the EqualFold predicate on the "source_rel" field.
func SourceRelEqualFold(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEqualFold(FieldSourceRel, v))
}

// SourceRelContainsFold applies the ContainsFold predicate on the "source_rel" field.
func SourceRelContainsFold(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldContainsFold(FieldSourceRel, v))
}

// RepoURLEQ applies the EQ predicate on the "repo_url" field.
func RepoURLEQ(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEQ(FieldRepoURL, v))
}

// RepoURLNEQ applies the NEQ predicate on the "repo_url" field.
func RepoURLNEQ(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNEQ(FieldRepoURL, v))
}

// RepoURLIn applies the In predicate on the "repo_url" field.
func RepoURLIn(vs ...string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldIn(FieldRepoURL, vs...))
}

// RepoURLNotIn applies the NotIn predicate on the "repo_url" field.
func RepoURLNotIn(vs ...string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNotIn(FieldRepoURL, vs...))
}

// RepoURLGT applies the GT predicate on the "repo_url" field.
func RepoURLGT(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldGT(FieldRepoURL, v))
}

// RepoURLGTE applies the GTE predicate on the "repo_url" field.
func RepoURLGTE(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldGTE(FieldRepoURL, v))
}

// RepoURLLT applies the LT predicate on the "repo_url" field.
func RepoURLLT(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldLT(FieldRepoURL, v))
}

// RepoURLLTE applies the LTE predicate on the "repo_url" field.
func RepoURLLTE(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldLTE(FieldRepoURL, v))
}

// RepoURLContains applies the Contains predicate on the "repo_url" field.
func RepoURLContains(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldContains(FieldRepoURL, v))
}

// RepoURLHasPrefix applies the HasPrefix predicate on the "repo_url" field.
func RepoURLHasPrefix(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldHasPrefix(FieldRepoURL, v))
}

// RepoURLHasSuffix applies the HasSuffix predicate on the "repo_url" field.
func RepoURLHasSuffix(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldHasSuffix(FieldRepoURL, v))
}

// RepoURLEqualFold applies the EqualFold predicate on the "repo_url" field.
func RepoURLEqualFold(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEqualFold(FieldRepoURL, v))
}

// RepoURLContainsFold applies the ContainsFold predicate on the "repo_url" field.
func RepoURLContainsFold(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldContainsFold(FieldRepoURL, v))
}

// TargetRelEQ applies the EQ predicate on the "target_rel" field.
func TargetRelEQ(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEQ(FieldTargetRel, v))
}

// TargetRelNEQ applies the NEQ predicate on the "target_rel" field.
func TargetRelNEQ(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNEQ(FieldTargetRel, v))
}

// TargetRelIn applies the In predicate on the "target_rel" field.
func TargetRelIn(vs ...string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldIn(FieldTargetRel, vs...))
}

// TargetRelNotIn applies the NotIn predicate on the "target_rel" field.
func TargetRelNotIn(vs ...string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNotIn(FieldTargetRel, vs...))
}

// TargetRelGT applies the GT predicate on the "target_rel" field.
func TargetRelGT(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldGT(FieldTargetRel, v))
}

// TargetRelGTE applies the GTE predicate on the "target_rel" field.
func TargetRelGTE(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldGTE(FieldTargetRel, v))
}

// TargetRelLT applies the LT predicate on the "target_rel" field.
func TargetRelLT(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldLT(FieldTargetRel, v))
}

// TargetRelLTE applies the LTE predicate on the "target_rel" field.
func TargetRelLTE(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldLTE(FieldTargetRel, v))
}

// TargetRelContains applies the Contains predicate on the "target_rel" field.
func TargetRelContains(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldContains(FieldTargetRel, v))
}

// TargetRelHasPrefix applies the HasPrefix predicate on the "target_rel" field.
func TargetRelHasPrefix(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldHasPrefix(FieldTargetRel, v))
}

// TargetRelHasSuffix applies the HasSuffix predicate on the "target_rel" field.
func TargetRelHasSuffix(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldHasSuffix(FieldTargetRel, v))
}

// TargetRelEqualFold applies the EqualFold predicate on the "target_rel" field.
func TargetRelEqualFold(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEqualFold(FieldTargetRel, v))
}

// TargetRelContainsFold applies the ContainsFold predicate on the "target_rel" field.
func TargetRelContainsFold(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldContainsFold(FieldTargetRel, v))
}

// LinkNameEQ applies the EQ predicate on the "link_name" field.
func LinkNameEQ(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEQ(FieldLinkName, v))
}

// LinkNameNEQ applies the NEQ predicate on the "link_name" field.
func LinkNameNEQ(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNEQ(FieldLinkName, v))
}

// LinkNameIn applies the In predicate on the "link_name" field.
func LinkNameIn(vs ...string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldIn(FieldLinkName, vs...))
}

// LinkNameNotIn applies the NotIn predicate on the "link_name" field.
func LinkNameNotIn(vs ...string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNotIn(FieldLinkName, vs...))
}

// LinkNameGT applies the GT predicate on the "link_name" field.
func LinkNameGT(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldGT(FieldLinkName, v))
}

// LinkNameGTE applies the GTE predicate on the "link_name" field.
func LinkNameGTE(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldGTE(FieldLinkName, v))
}

// LinkNameLT applies the LT predicate on the "link_name" field.
func LinkNameLT(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldLT(FieldLinkName, v))
}

// LinkNameLTE applies the LTE predicate on the "link_name" field.
func LinkNameLTE(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldLTE(FieldLinkName, v))
}

// LinkNameContains applies the Contains predicate on the "link_name" field.
func LinkNameContains(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldContains(FieldLinkName, v))
}

// LinkNameHasPrefix applies the HasPrefix predicate on the "link_name" field.
func LinkNameHasPrefix(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldHasPrefix(FieldLinkName, v))
}

// LinkNameHasSuffix applies the HasSuffix predicate on the "link_name" field.
func LinkNameHasSuffix(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldHasSuffix(FieldLinkName, v))
}

// LinkNameEqualFold applies the EqualFold predicate on the "link_name" field.
func LinkNameEqualFold(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEqualFold(FieldLinkName, v))
}

// LinkNameContainsFold applies the ContainsFold predicate on the "link_name" field.
func LinkNameContainsFold(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldContainsFold(FieldLinkName, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v Kind) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v Kind) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...Kind) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...Kind) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNotIn(FieldKind, vs...))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v State) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v State) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...State) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...State) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNotIn(FieldState, vs...))
}

// CreatedByEmailEQ applies the EQ predicate on the "created_by_email" field.
func CreatedByEmailEQ(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEQ(FieldCreatedByEmail, v))
}

// CreatedByEmailNEQ applies the NEQ predicate on the "created_by_email" field.
func CreatedByEmailNEQ(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNEQ(FieldCreatedByEmail, v))
}

// CreatedByEmailIn applies the In predicate on the "created_by_email" field.
func CreatedByEmailIn(vs ...string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldIn(FieldCreatedByEmail, vs...))
}

// CreatedByEmailNotIn applies the NotIn predicate on the "created_by_email" field.
func CreatedByEmailNotIn(vs ...string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNotIn(FieldCreatedByEmail, vs...))
}

// CreatedByEmailGT applies the GT predicate on the "created_by_email" field.
func CreatedByEmailGT(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldGT(FieldCreatedByEmail, v))
}

// CreatedByEmailGTE applies the GTE predicate on the "created_by_email" field.
func CreatedByEmailGTE(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldGTE(FieldCreatedByEmail, v))
}

// CreatedByEmailLT applies the LT predicate on the "created_by_email" field.
func CreatedByEmailLT(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldLT(FieldCreatedByEmail, v))
}

// CreatedByEmailLTE applies the LTE predicate on the "created_by_email" field.
func CreatedByEmailLTE(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldLTE(FieldCreatedByEmail, v))
}

// CreatedByEmailContains applies the Contains predicate on the "created_by_email" field.
func CreatedByEmailContains(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldContains(FieldCreatedByEmail, v))
}

// CreatedByEmailHasPrefix applies the HasPrefix predicate on the "created_by_email" field.
func CreatedByEmailHasPrefix(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldHasPrefix(FieldCreatedByEmail, v))
}

// CreatedByEmailHasSuffix applies the HasSuffix predicate on the "created_by_email" field.
func CreatedByEmailHasSuffix(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldHasSuffix(FieldCreatedByEmail, v))
}

// CreatedByEmailIsNil applies the IsNil predicate on the "created_by_email" field.
func CreatedByEmailIsNil() predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldIsNull(FieldCreatedByEmail))
}

// CreatedByEmailNotNil applies the NotNil predicate on the "created_by_email" field.
func CreatedByEmailNotNil() predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNotNull(FieldCreatedByEmail))
}

// CreatedByEmailEqualFold applies the EqualFold predicate on the "created_by_email" field.
func CreatedByEmailEqualFold(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEqualFold(FieldCreatedByEmail, v))
}

// CreatedByEmailContainsFold applies the ContainsFold predicate on the "created_by_email" field.
func CreatedByEmailContainsFold(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldContainsFold(FieldCreatedByEmail, v))
}

// CreatedByNameEQ applies the EQ predicate on the "created_by_name" field.
func CreatedByNameEQ(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEQ(FieldCreatedByName, v))
}

// CreatedByNameNEQ applies the NEQ predicate on the "created_by_name" field.
func CreatedByNameNEQ(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNEQ(FieldCreatedByName, v))
}

// CreatedByNameIn applies the In predicate on the "created_by_name" field.
func CreatedByNameIn(vs ...string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldIn(FieldCreatedByName, vs...))
}

// CreatedByNameNotIn applies the NotIn predicate on the "created_by_name" field.
func CreatedByNameNotIn(vs ...string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNotIn(FieldCreatedByName, vs...))
}

// CreatedByNameGT applies the GT predicate on the "created_by_name" field.
func CreatedByNameGT(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldGT(FieldCreatedByName, v))
}

// CreatedByNameGTE applies the GTE predicate on the "created_by_name" field.
func CreatedByNameGTE(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldGTE(FieldCreatedByName, v))
}

// CreatedByNameLT applies the LT predicate on the "created_by_name" field.
func CreatedByNameLT(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldLT(FieldCreatedByName, v))
}

// CreatedByNameLTE applies the LTE predicate on the "created_by_name" field.
func CreatedByNameLTE(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldLTE(FieldCreatedByName, v))
}

// CreatedByNameContains applies the Contains predicate on the "created_by_name" field.
func CreatedByNameContains(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldContains(FieldCreatedByName, v))
}

// CreatedByNameHasPrefix applies the HasPrefix predicate on the "created_by_name" field.
func CreatedByNameHasPrefix(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldHasPrefix(FieldCreatedByName, v))
}

// CreatedByNameHasSuffix applies the HasSuffix predicate on the "created_by_name" field.
func CreatedByNameHasSuffix(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldHasSuffix(FieldCreatedByName, v))
}

// CreatedByNameIsNil applies the IsNil predicate on the "created_by_name" field.
func CreatedByNameIsNil() predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldIsNull(FieldCreatedByName))
}

// CreatedByNameNotNil applies the NotNil predicate on the "created_by_name" field.
func CreatedByNameNotNil() predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNotNull(FieldCreatedByName))
}

// CreatedByNameEqualFold applies the EqualFold predicate on the "created_by_name" field.
func CreatedByNameEqualFold(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEqualFold(FieldCreatedByName, v))
}

// CreatedByNameContainsFold applies the ContainsFold predicate on the "created_by_name" field.
func CreatedByNameContainsFold(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldContainsFold(FieldCreatedByName, v))
}

// UpdatedByEmailEQ applies the EQ predicate on the "updated_by_email" field.
func UpdatedByEmailEQ(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEQ(FieldUpdatedByEmail, v))
}

// UpdatedByEmailNEQ applies the NEQ predicate on the "updated_by_email" field.
func UpdatedByEmailNEQ(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNEQ(FieldUpdatedByEmail, v))
}

// UpdatedByEmailIn applies the In predicate on the "updated_by_email" field.
func UpdatedByEmailIn(vs ...string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldIn(FieldUpdatedByEmail, vs...))
}

// UpdatedByEmailNotIn applies the NotIn predicate on the "updated_by_email" field.
func UpdatedByEmailNotIn(vs ...string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNotIn(FieldUpdatedByEmail, vs...))
}

// UpdatedByEmailGT applies the GT predicate on the "updated_by_email" field.
func UpdatedByEmailGT(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldGT(FieldUpdatedByEmail, v))
}

// UpdatedByEmailGTE applies the GTE predicate on the "updated_by_email" field.
func UpdatedByEmailGTE(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldGTE(FieldUpdatedByEmail, v))
}

// UpdatedByEmailLT applies the LT predicate on the "updated_by_email" field.
func UpdatedByEmailLT(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldLT(FieldUpdatedByEmail, v))
}

// UpdatedByEmailLTE applies the LTE predicate on the "updated_by_email" field.
func UpdatedByEmailLTE(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldLTE(FieldUpdatedByEmail, v))
}

// UpdatedByEmailContains applies the Contains predicate on the "updated_by_email" field.
func UpdatedByEmailContains(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldContains(FieldUpdatedByEmail, v))
}

// UpdatedByEmailHasPrefix applies the HasPrefix predicate on the "updated_by_email" field.
func UpdatedByEmailHasPrefix(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldHasPrefix(FieldUpdatedByEmail, v))
}

// UpdatedByEmailHasSuffix applies the HasSuffix predicate on the "updated_by_email" field.
func UpdatedByEmailHasSuffix(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldHasSuffix(FieldUpdatedByEmail, v))
}

// UpdatedByEmailIsNil applies the IsNil predicate on the "updated_by_email" field.
func UpdatedByEmailIsNil() predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldIsNull(FieldUpdatedByEmail))
}

// UpdatedByEmailNotNil applies the NotNil predicate on the "updated_by_email" field.
func UpdatedByEmailNotNil() predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNotNull(FieldUpdatedByEmail))
}

// UpdatedByEmailEqualFold applies the EqualFold predicate on the "updated_by_email" field.
func UpdatedByEmailEqualFold(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEqualFold(FieldUpdatedByEmail, v))
}

// UpdatedByEmailContainsFold applies the ContainsFold predicate on the "updated_by_email" field.
func UpdatedByEmailContainsFold(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldContainsFold(FieldUpdatedByEmail, v))
}

// UpdatedByNameEQ applies the EQ predicate on the "updated_by_name" field.
func UpdatedByNameEQ(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEQ(FieldUpdatedByName, v))
}

// UpdatedByNameNEQ applies the NEQ predicate on the "updated_by_name" field.
func UpdatedByNameNEQ(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNEQ(FieldUpdatedByName, v))
}

// UpdatedByNameIn applies the In predicate on the "updated_by_name" field.
func UpdatedByNameIn(vs ...string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldIn(FieldUpdatedByName, vs...))
}

// UpdatedByNameNotIn applies the NotIn predicate on the "updated_by_name" field.
func UpdatedByNameNotIn(vs ...string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNotIn(FieldUpdatedByName, vs...))
}

// UpdatedByNameGT applies the GT predicate on the "updated_by_name" field.
func UpdatedByNameGT(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldGT(FieldUpdatedByName, v))
}

// UpdatedByNameGTE applies the GTE predicate on the "updated_by_name" field.
func UpdatedByNameGTE(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldGTE(FieldUpdatedByName, v))
}

// UpdatedByNameLT applies the LT predicate on the "updated_by_name" field.
func UpdatedByNameLT(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldLT(FieldUpdatedByName, v))
}

// UpdatedByNameLTE applies the LTE predicate on the "updated_by_name" field.
func UpdatedByNameLTE(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldLTE(FieldUpdatedByName, v))
}

// UpdatedByNameContains applies the Contains predicate on the "updated_by_name" field.
func UpdatedByNameContains(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldContains(FieldUpdatedByName, v))
}

// UpdatedByNameHasPrefix applies the HasPrefix predicate on the "updated_by_name" field.
func UpdatedByNameHasPrefix(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldHasPrefix(FieldUpdatedByName, v))
}

// UpdatedByNameHasSuffix applies the HasSuffix predicate on the "updated_by_name" field.
func UpdatedByNameHasSuffix(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldHasSuffix(FieldUpdatedByName, v))
}

// UpdatedByNameIsNil applies the IsNil predicate on the "updated_by_name" field.
func UpdatedByNameIsNil() predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldIsNull(FieldUpdatedByName))
}

// UpdatedByNameNotNil applies the NotNil predicate on the "updated_by_name" field.
func UpdatedByNameNotNil() predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNotNull(FieldUpdatedByName))
}

// UpdatedByNameEqualFold applies the EqualFold predicate on the "updated_by_name" field.
func UpdatedByNameEqualFold(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEqualFold(FieldUpdatedByName, v))
}

// UpdatedByNameContainsFold applies the ContainsFold predicate on the "updated_by_name" field.
func UpdatedByNameContainsFold(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldContainsFold(FieldUpdatedByName, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldContainsFold(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RepoMapping {
	return predicate.RepoMapping(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RepoMapping) predicate.RepoMapping {
	return predicate.RepoMapping(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RepoMapping) predicate.RepoMapping {
	return predicate.RepoMapping(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RepoMapping) predicate.RepoMapping {
	return predicate.RepoMapping(sql.NotPredicates(p))
}
